
export const data = [
    {
        id: '1f10330f-ebae-483e-b308-2db3176fdef6',
        name_en: 'Медальоны с оващами гриль',
        name_kg: 'Медальоны с оващами гриль',
        name_ru: 'Медальоны с оващами гриль',
        description_en: '',
        description_kg: '',
        description_ru: '',
        price: 480,
        gram: '',
        category_name: 'Вторые блюда из говядины',
        image: 'http://192.168.0.160:8000/media/dishes/407e435b469e6882e7ff52a9effd9e0d---jpg_1000x_103c0_convert.jpg',
        available_additives: []
    },
    {
        id: '11e0afbd-6c13-46db-af5d-391a7494eb58',
        name_en: 'Стейк из семги',
        name_kg: 'Стейк из семги',
        name_ru: 'Стейк из семги',
        description_en: '',
        description_kg: '',
        description_ru: '',
        price: 750,
        gram: '',
        category_name: 'Вторые блюда из рыбы',
        image: 'http://192.168.0.160:8000/media/dishes/bf6602b7_3M2PIXF.jpg',
        available_additives: []
    },
    {
        id: '67ae0b3c-338d-4205-ba4c-841f0351199d',
        name_en: 'Курица в соусе "Карри" с рисом',
        name_kg: 'Курица в соусе "Карри" с рисом',
        name_ru: 'Курица в соусе "Карри" с рисом',
        description_en: '',
        description_kg: '',
        description_ru: '',
        price: 370,
        gram: '',
        category_name: 'Вторые блюда из курицы',
        image: 'http://192.168.0.160:8000/media/dishes/7baada.jpg',
        available_additives: []
    },
    {
        id: '49fe476f-47d2-47de-80ba-f86f8444d1b7',
        name_en: 'Филе из форели',
        name_kg: 'Филе из форели',
        name_ru: 'Филе из форели',
        description_en: '',
        description_kg: '',
        description_ru: '',
        price: 370,
        gram: '',
        category_name: 'Вторые блюда из рыбы',
        image: 'http://192.168.0.160:8000/media/dishes/recept-30469-620x413_w_GwyMxgj.jpg',
        available_additives: []
    },
    {
        id: 'ce095efb-f49d-4c01-b2d2-2ac44b3881d2',
        name_en: 'Форель радужная',
        name_kg: 'Форель радужная',
        name_ru: 'Форель радужная',
        description_en: '',
        description_kg: '',
        description_ru: '',
        price: 460,
        gram: '',
        category_name: 'Вторые блюда из рыбы',
        image: 'http://192.168.0.160:8000/media/dishes/rainbow-trout-in-the-foil_2O2WkOY.jpg',
        available_additives: []
    },
    {
        id: 'e7e2b5a3-00ec-4b48-8ce9-d6fe2d7e43d1',
        name_en: 'Ребрышки',
        name_kg: 'Ребрышки',
        name_ru: 'Ребрышки',
        description_en: '',
        description_kg: '',
        description_ru: '',
        price: 400,
        gram: '',
        category_name: 'Вторые блюда из говядины',
        image: 'http://192.168.0.160:8000/media/dishes/80452-ed4_wide.jpg',
        available_additives: []
    },
    {
        id: 'd09a4ab2-157d-4d83-8c73-2c6dcc5e55c4',
        name_en: 'Баранина кебаб со сливочным соусом',
        name_kg: 'Баранина кебаб со сливочным соусом',
        name_ru: 'Баранина кебаб со сливочным соусом',
        description_en: '',
        description_kg: '',
        description_ru: '',
        price: 370,
        gram: '',
        category_name: 'Вторые блюда из баранины',
        image: 'http://192.168.0.160:8000/media/dishes/u-1a8b0c34787e5e9ea0e70b41899cf66d.jpg',
        available_additives: []
    },
    {
        id: '9716c0ea-6e19-4f68-8a61-4f5af6fdefc6',
        name_en: 'Семга под икорным соусом',
        name_kg: 'Семга под икорным соусом',
        name_ru: 'Семга под икорным соусом',
        description_en: '',
        description_kg: '',
        description_ru: '',
        price: 480,
        gram: '',
        category_name: 'Вторые блюда из рыбы',
        image: 'http://192.168.0.160:8000/media/dishes/893_0193br3_0853_1024.jpg',
        available_additives: []
    },
    {
        id: 'c556ab5e-7ed3-48b6-bfeb-9ee980454999',
        name_en: 'Рибай',
        name_kg: 'Рибай',
        name_ru: 'Рибай',
        description_en: '',
        description_kg: '',
        description_ru: '',
        price: 550,
        gram: '',
        category_name: 'Вторые блюда из говядины',
        image: 'http://192.168.0.160:8000/media/dishes/47581.jpg',
        available_additives: []
    },
    {
        id: '4fd34bbe-fa47-4390-9135-9e26a6f2f719',
        name_en: 'Стейк из баранины',
        name_kg: 'Стейк из баранины',
        name_ru: 'Стейк из баранины',
        description_en: '',
        description_kg: '',
        description_ru: '',
        price: 450,
        gram: '',
        category_name: 'Вторые блюда из баранины',
        image: 'http://192.168.0.160:8000/media/dishes/steik-iz-baraniny_1538226183_1_max.jpg',
        available_additives: []
    },
    {
        id: 'fedbd01a-64af-49d4-b1fc-afb06b496ac7',
        name_en: 'Т-бон стейк',
        name_kg: 'Т-бон стейк',
        name_ru: 'Т-бон стейк',
        description_en: '',
        description_kg: '',
        description_ru: '',
        price: 550,
        gram: '',
        category_name: 'Вторые блюда из говядины',
        image: 'http://192.168.0.160:8000/media/dishes/338ior.jpg',
        available_additives: []
    },
    {
        id: 'ef355a1e-89aa-4f53-8345-81dc69b87851',
        name_en: 'Нью йорк стейк',
        name_kg: 'Нью йорк стейк',
        name_ru: 'Нью йорк стейк',
        description_en: '',
        description_kg: '',
        description_ru: '',
        price: 400,
        gram: '',
        category_name: 'Вторые блюда из говядины',
        image: 'http://192.168.0.160:8000/media/dishes/a6fc538f39d05e73b3985723f33e0784.jpg',
        available_additives: []
    },
    {
        id: '6907cdd3-6081-479f-955a-57f4f634d30a',
        name_en: 'Ассорти погребок',
        name_kg: 'Ассорти погребок',
        name_ru: 'Ассорти погребок',
        description_en: '(селед,шпроты,корниш,черри,опята,грузди,кваш,кап,карт,клинья,лук реп,хлеб бородинский)',
        description_kg: '(селед,шпроты,корниш,черри,опята,грузди,кваш,кап,карт,клинья,лук реп,хлеб бородинский)',
        description_ru: '(селед,шпроты,корниш,черри,опята,грузди,кваш,кап,карт,клинья,лук реп,хлеб бородинский)',
        price: 830,
        gram: '',
        category_name: 'Холодные закуски',
        image: 'http://192.168.0.160:8000/media/dishes/zakuska-pogrebok.800x600w.jpg',
        available_additives: []
    },
    {
        id: 'f006e908-23c1-4359-833a-709458118ae3',
        name_en: 'Куриные отбиваные под сыром',
        name_kg: 'Куриные отбиваные под сыром',
        name_ru: 'Куриные отбиваные под сыром',
        description_en: '',
        description_kg: '',
        description_ru: '',
        price: 340,
        gram: '',
        category_name: 'Вторые блюда из курицы',
        image: 'http://192.168.0.160:8000/media/dishes/kurinye-otbivnye-s-syrom-v-duxovke_1538302173_10_max.jpg',
        available_additives: []
    },
    {
        id: '97871dc8-edd7-4054-b636-87f691b80cbd',
        name_en: 'Бараньи ребрышки с овощами',
        name_kg: 'Бараньи ребрышки с овощами',
        name_ru: 'Бараньи ребрышки с овощами',
        description_en: '',
        description_kg: '',
        description_ru: '',
        price: 480,
        gram: '',
        category_name: 'Вторые блюда из баранины',
        image: 'http://192.168.0.160:8000/media/dishes/15707100270049.jpg',
        available_additives: []
    },
    {
        id: '7d5dc6d6-0fae-48c2-b518-f1b32466fa7e',
        name_en: 'Дуэт из телятины и курицы с оващими',
        name_kg: 'Дуэт из телятины и курицы с оващими',
        name_ru: 'Дуэт из телятины и курицы с оващими',
        description_en: '',
        description_kg: '',
        description_ru: '',
        price: 450,
        gram: '',
        category_name: 'Вторые блюда из говядины',
        image: 'http://192.168.0.160:8000/media/dishes/k-1618-00.jpg',
        available_additives: []
    },
    {
        id: 'e511b678-3def-4335-ade4-c430bd388d75',
        name_en: 'Охотничий сет',
        name_kg: 'Охотничий сет',
        name_ru: 'Охотничий сет',
        description_en: '(колб,кур,телят,баран,охот,соусБарб.)',
        description_kg: '(колб,кур,телят,баран,охот,соусБарб.)',
        description_ru: '(колб,кур,телят,баран,охот,соусБарб.)',
        price: 900,
        gram: '',
        category_name: 'Холодные закуски',
        image: 'http://192.168.0.160:8000/media/dishes/5d5fdc9918144.jpg',
        available_additives: []
    },
    {
        id: '068a20a6-6a94-4264-9dd8-c21d13d902f2',
        name_en: 'Телятина толедо',
        name_kg: 'Телятина толедо',
        name_ru: 'Телятина толедо',
        description_en: '',
        description_kg: '',
        description_ru: '',
        price: 390,
        gram: '',
        category_name: 'Вторые блюда из говядины',
        image: 'http://192.168.0.160:8000/media/dishes/150329.png',
        available_additives: []
    },
    {
        id: 'eb60b482-957e-4a96-bc17-7f622566d230',
        name_en: 'Фарш грудко со шпинатом и сыром',
        name_kg: 'Фарш грудко со шпинатом и сыром',
        name_ru: 'Фарш грудко со шпинатом и сыром',
        description_en: '',
        description_kg: '',
        description_ru: '',
        price: 350,
        gram: '',
        category_name: 'Вторые блюда из курицы',
        image: 'http://192.168.0.160:8000/media/dishes/49_1636992483-scaled-e1636992539507-1280x640.jpg',
        available_additives: []
    },
    {
        id: '372e5ff6-73fe-4161-967b-4c18eb916b58',
        name_en: 'Цыпленок табака',
        name_kg: 'Цыпленок табака',
        name_ru: 'Цыпленок табака',
        description_en: '',
        description_kg: '',
        description_ru: '',
        price: 380,
        gram: '',
        category_name: 'Вторые блюда из курицы',
        image: 'http://192.168.0.160:8000/media/dishes/big_352829.jpg',
        available_additives: []
    },
    {
        id: 'afe89c1c-5373-426b-bdfd-0aa018360fac',
        name_en: 'Куриные медальоны',
        name_kg: 'Куриные медальоны',
        name_ru: 'Куриные медальоны',
        description_en: '',
        description_kg: '',
        description_ru: '',
        price: 340,
        gram: '',
        category_name: 'Вторые блюда из курицы',
        image: 'http://192.168.0.160:8000/media/dishes/5ea1ca7e3577c.jpg',
        available_additives: []
    },
    {
        id: '1669c374-b577-4df0-84ee-57b9ee6d5589',
        name_en: 'Наггетсы',
        name_kg: 'Наггетсы',
        name_ru: 'Наггетсы',
        description_en: '',
        description_kg: '',
        description_ru: '',
        price: 300,
        gram: '',
        category_name: 'Холодные закуски',
        image: 'http://192.168.0.160:8000/media/dishes/Air-Fryer-Chicken-Nuggets-sq.jpg',
        available_additives: []
    },
    {
        id: '11962812-fb43-4803-bea1-93f8d9f99154',
        name_en: 'Погребок',
        name_kg: 'Погребок',
        name_ru: 'Погребок',
        description_en: '(Маррин,опята,помид,черри,патис,корниш,кукур,початки,грузди,лист.салата)',
        description_kg: '(Маррин,опята,помид,черри,патис,корниш,кукур,початки,грузди,лист.салата)',
        description_ru: '(Маррин,опята,помид,черри,патис,корниш,кукур,початки,грузди,лист.салата)',
        price: 380,
        gram: '',
        category_name: 'Холодные закуски',
        image: 'http://192.168.0.160:8000/media/dishes/BABUSHKINY-SOLENYA.png',
        available_additives: []
    },
    {
        id: '8240f8d1-b6f3-4a72-95bd-ab57dd3c8979',
        name_en: 'Сельдь по русски',
        name_kg: 'Сельдь по русски',
        name_ru: 'Сельдь по русски',
        description_en: '(Сельдь,карт.,Корниш.,Лук репч., Черри помид)',
        description_kg: '(Сельдь,карт.,Корниш.,Лук репч., Черри помид)',
        description_ru: '(Сельдь,карт.,Корниш.,Лук репч., Черри помид)',
        price: 350,
        gram: '',
        category_name: 'Холодные закуски',
        image: 'http://192.168.0.160:8000/media/dishes/D181D0B5D0BBD18CD0B4D18C-500x500.jpg',
        available_additives: []
    },
    {
        id: 'fec308b5-b53c-4301-9866-eedd7937560c',
        name_en: 'Кавказский с овощами',
        name_kg: 'Кавказский с овощами',
        name_ru: 'Кавказский с овощами',
        description_en: '',
        description_kg: '',
        description_ru: '',
        price: 320,
        gram: '',
        category_name: 'Шашлыки',
        image: 'http://192.168.0.160:8000/media/dishes/salat-tbilisi-s-govyadinoj-i-fasolyu.jpg',
        available_additives: []
    },
    {
        id: '3bafc44f-3869-4c68-b765-15764074a3a1',
        name_en: 'Люля кебаб',
        name_kg: 'Люля кебаб',
        name_ru: 'Люля кебаб',
        description_en: '',
        description_kg: '',
        description_ru: '',
        price: 310,
        gram: '',
        category_name: 'Шашлыки',
        image: 'http://192.168.0.160:8000/media/dishes/big_516241.jpg',
        available_additives: []
    },
    {
        id: '1eb896b2-47da-4af5-ae34-aa93c8261d26',
        name_en: 'Рулет из баклажана',
        name_kg: 'Рулет из баклажана',
        name_ru: 'Рулет из баклажана',
        description_en: '(Бакл.., Брынза,Помидю,Огурцы)',
        description_kg: '(Бакл.., Брынза,Помидю,Огурцы)',
        description_ru: '(Бакл.., Брынза,Помидю,Огурцы)',
        price: 370,
        gram: '',
        category_name: 'Холодные закуски',
        image: 'http://192.168.0.160:8000/media/dishes/035c26a3b5.JPG',
        available_additives: []
    },
    {
        id: 'c03b4456-5c8b-4454-958e-29c79b47eca8',
        name_en: 'Ассорти "Национальное"',
        name_kg: 'Ассорти "Национальное"',
        name_ru: 'Ассорти "Национальное"',
        description_en: '(Чучук,казы-карта,конина,зелень,черри)',
        description_kg: '(Чучук,казы-карта,конина,зелень,черри)',
        description_ru: '(Чучук,казы-карта,конина,зелень,черри)',
        price: 1050,
        gram: '',
        category_name: 'Холодные закуски',
        image: 'http://192.168.0.160:8000/media/dishes/assorti-nacionalnoe.800x600w.png',
        available_additives: []
    },
    {
        id: 'e754d77d-ad28-4b7d-adc3-c7a59ff9780b',
        name_en: 'Рулет с кабачками',
        name_kg: 'Рулет с кабачками',
        name_ru: 'Рулет с кабачками',
        description_en: '(Кабачки.,Брынза,помид,огурцы.)',
        description_kg: '(Кабачки.,Брынза,помид,огурцы.)',
        description_ru: '(Кабачки.,Брынза,помид,огурцы.)',
        price: 370,
        gram: '',
        category_name: 'Холодные закуски',
        image: 'http://192.168.0.160:8000/media/dishes/rulet-iz-kabachkov-s-pomidorami_1539181411_2_max.jpg',
        available_additives: []
    },
    {
        id: '238565ee-6b4c-40e9-980f-ed669d379975',
        name_en: 'Деревенский',
        name_kg: 'Деревенский',
        name_ru: 'Деревенский',
        description_en: '(Курин,груд,,огурцы,сыр,тильз.,опята марин.,яйцо,кукуруза)',
        description_kg: '(Курин,груд,,огурцы,сыр,тильз.,опята марин.,яйцо,кукуруза)',
        description_ru: '(Курин,груд,,огурцы,сыр,тильз.,опята марин.,яйцо,кукуруза)',
        price: 360,
        gram: '250',
        category_name: 'Салаты с майонезом',
        image: 'http://192.168.0.160:8000/media/dishes/maxresdefault.jpg',
        available_additives: []
    },
    {
        id: '1666099e-1d33-4fc9-9ef8-02ddc40d4e42',
        name_en: 'Ассорти "Русалочка"',
        name_kg: 'Ассорти "Русалочка"',
        name_ru: 'Ассорти "Русалочка"',
        description_en: '(Скумбрия,эсколар,семга,лимон,тарталетки,твор.сыр,икра)',
        description_kg: '(Скумбрия,эсколар,семга,лимон,тарталетки,твор.сыр,икра)',
        description_ru: '(Скумбрия,эсколар,семга,лимон,тарталетки,твор.сыр,икра)',
        price: 1050,
        gram: '',
        category_name: 'Холодные закуски',
        image: 'http://192.168.0.160:8000/media/dishes/77948.png',
        available_additives: []
    },
    {
        id: '0994330b-a8f1-4ea7-bb5d-39ad1ea353b2',
        name_en: 'Сырные палочки',
        name_kg: 'Сырные палочки',
        name_ru: 'Сырные палочки',
        description_en: '(Голландский сыр,медово горчичный соус)',
        description_kg: '(Голландский сыр,медово горчичный соус)',
        description_ru: '(Голландский сыр,медово горчичный соус)',
        price: 360,
        gram: '',
        category_name: 'Холодные закуски',
        image: 'http://192.168.0.160:8000/media/dishes/shutterstock_1154255068_1577700632-e1578638356632-1280x640.jpg',
        available_additives: []
    },
    {
        id: 'e8314062-9f35-40f7-af62-0f846da381ab',
        name_en: 'Ассорти "Европейское"',
        name_kg: 'Ассорти "Европейское"',
        name_ru: 'Ассорти "Европейское"',
        description_en: '(Мясн.рулет,курин.рулет,язык,бастурма)',
        description_kg: '(Мясн.рулет,курин.рулет,язык,бастурма)',
        description_ru: '(Мясн.рулет,курин.рулет,язык,бастурма)',
        price: 700,
        gram: '',
        category_name: 'Холодные закуски',
        image: 'http://192.168.0.160:8000/media/dishes/1582915043.jpg',
        available_additives: []
    },
    {
        id: '80de1fb4-853d-42d5-b942-6f290eefe583',
        name_en: 'Лора',
        name_kg: 'Лора',
        name_ru: 'Лора',
        description_en: '(Куриная грудка,ананас,сыр тильзитский,опята марин.,яйца)',
        description_kg: '(Куриная грудка,ананас,сыр тильзитский,опята марин.,яйца)',
        description_ru: '(Куриная грудка,ананас,сыр тильзитский,опята марин.,яйца)',
        price: 360,
        gram: '250',
        category_name: 'Салаты с майонезом',
        image: 'http://192.168.0.160:8000/media/dishes/salat_lora_s_baklajanami-756594.JPG',
        available_additives: []
    },
    {
        id: 'dd4d20e1-9ea7-4b6e-a289-3c787d363bce',
        name_en: 'Ассорти "Кавказское"',
        name_kg: 'Ассорти "Кавказское"',
        name_ru: 'Ассорти "Кавказское"',
        description_en: '(Помид.свежие,огур.,болг.перец,киназа,зелен.лук,брынза)',
        description_kg: '(Помид.свежие,огур.,болг.перец,киназа,зелен.лук,брынза)',
        description_ru: '(Помид.свежие,огур.,болг.перец,киназа,зелен.лук,брынза)',
        price: 380,
        gram: '',
        category_name: 'Холодные закуски',
        image: 'http://192.168.0.160:8000/media/dishes/k69a0347.jpg',
        available_additives: []
    },
    {
        id: 'b3f53225-8ff6-45c2-8958-9d018a4634b6',
        name_en: 'Оливье',
        name_kg: 'Оливье',
        name_ru: 'Оливье',
        description_en: '(Доктор.колбоса халал,огурц.марин.,яйцо,картофель,морковь,зеленый горох)',
        description_kg: '(Доктор.колбоса халал,огурц.марин.,яйцо,картофель,морковь,зеленый горох)',
        description_ru: '(Доктор.колбоса халал,огурц.марин.,яйцо,картофель,морковь,зеленый горох)',
        price: 260,
        gram: '250',
        category_name: 'Салаты с майонезом',
        image: 'http://192.168.0.160:8000/media/dishes/b9d2e6d3.jpeg',
        available_additives: []
    },
    {
        id: 'e60db6ea-9294-4d7a-945d-c67aff919e55',
        name_en: 'Грибной',
        name_kg: 'Грибной',
        name_ru: 'Грибной',
        description_en: '(Кур.груд.,жар.вешенки,шампиньоны,помид.,сельд.)',
        description_kg: '(Кур.груд.,жар.вешенки,шампиньоны,помид.,сельд.)',
        description_ru: '(Кур.груд.,жар.вешенки,шампиньоны,помид.,сельд.)',
        price: 340,
        gram: '250',
        category_name: 'Салаты с майонезом',
        image: 'http://192.168.0.160:8000/media/dishes/7_1574415972-e1574415999301-630x315.jpg',
        available_additives: []
    },
    {
        id: 'ae8befec-22e5-4913-9fc8-2330abbd8725',
        name_en: 'Луна',
        name_kg: 'Луна',
        name_ru: 'Луна',
        description_en: '(Свекла,сыр голанск.,майон.,сыр пармезан,чеснок)',
        description_kg: '(Свекла,сыр голанск.,майон.,сыр пармезан,чеснок)',
        description_ru: '(Свекла,сыр голанск.,майон.,сыр пармезан,чеснок)',
        price: 320,
        gram: '250',
        category_name: 'Салаты с майонезом',
        image: 'http://192.168.0.160:8000/media/dishes/b41104385fba5e894902de571ef1e553.jpg',
        available_additives: []
    },
    {
        id: '6d058bc4-1897-4dbe-b0c1-52b54d286508',
        name_en: 'Фкуктовый салат',
        name_kg: 'Фкуктовый салат',
        name_ru: 'Фкуктовый салат',
        description_en: '(Соус,яблок.,апельс.,киви виногр.,гран.,мед,миск.салат)',
        description_kg: '(Соус,яблок.,апельс.,киви виногр.,гран.,мед,миск.салат)',
        description_ru: '(Соус,яблок.,апельс.,киви виногр.,гран.,мед,миск.салат)',
        price: 340,
        gram: '250',
        category_name: 'Салаты с майонезом',
        image: 'http://192.168.0.160:8000/media/dishes/fruktovyi-salat-001.jpg',
        available_additives: []
    },
    {
        id: 'c4f4b111-9292-4ff5-8a1b-3b7524f946cb',
        name_en: 'Салат чернослив',
        name_kg: 'Салат чернослив',
        name_ru: 'Салат чернослив',
        description_en: '(Мясо жарю,чернос.,перец болг., чери,микс сал.,песто соус)',
        description_kg: '(Мясо жарю,чернос.,перец болг., чери,микс сал.,песто соус)',
        description_ru: '(Мясо жарю,чернос.,перец болг., чери,микс сал.,песто соус)',
        price: 350,
        gram: '250',
        category_name: 'Салаты с растительным маслом',
        image: 'http://192.168.0.160:8000/media/dishes/2022-08-13-wj8b6i-salat-s-utinoy-grudkoy-chernoslivom-i-sirom-bri_756x0_62c.jpg',
        available_additives: []
    },
    {
        id: '75696023-6ef1-4851-8f51-d5e2c6d19180',
        name_en: 'Улуу тоо',
        name_kg: 'Улуу тоо',
        name_ru: 'Улуу тоо',
        description_en: '(Сырная корзина,цветная капуста в кляре,семга,лук,черри,микс салат,перец болг.,кукур)',
        description_kg: '(Сырная корзина,цветная капуста в кляре,семга,лук,черри,микс салат,перец болг.,кукур)',
        description_ru: '(Сырная корзина,цветная капуста в кляре,семга,лук,черри,микс салат,перец болг.,кукур)',
        price: 395,
        gram: '250',
        category_name: 'Салаты с растительным маслом',
        image: 'http://192.168.0.160:8000/media/dishes/108609.png',
        available_additives: []
    },
    {
        id: '7d4fab1c-39db-4a7f-b787-21add6abe343',
        name_en: 'Куриные крылья',
        name_kg: 'Куриные крылья',
        name_ru: 'Куриные крылья',
        description_en: '',
        description_kg: '',
        description_ru: '',
        price: 310,
        gram: '',
        category_name: 'Шашлыки',
        image: 'http://192.168.0.160:8000/media/dishes/22909-ed4_wide.jpg',
        available_additives: []
    },
    {
        id: '31b013c8-60e2-47e4-b5a9-6fccc5a698e8',
        name_en: 'Куриные голени',
        name_kg: 'Куриные голени',
        name_ru: 'Куриные голени',
        description_en: '',
        description_kg: '',
        description_ru: '',
        price: 310,
        gram: '',
        category_name: 'Шашлыки',
        image: 'http://192.168.0.160:8000/media/dishes/D0B3D0BED0BBD0B5D0BDD18C-min-600x400.jpg',
        available_additives: []
    },
    {
        id: '5b673df3-5cf7-4a85-98cf-e13292f973b4',
        name_en: 'Свекольный',
        name_kg: 'Свекольный',
        name_ru: 'Свекольный',
        description_en: '.(Свекла,морковь,орех грецкий,картофель,мясо,шампиньоны)',
        description_kg: '.(Свекла,морковь,орех грецкий,картофель,мясо,шампиньоны)',
        description_ru: '.(Свекла,морковь,орех грецкий,картофель,мясо,шампиньоны)',
        price: 330,
        gram: '250',
        category_name: 'Салаты с майонезом',
        image: 'http://192.168.0.160:8000/media/dishes/svekolnyy-salat.jpg',
        available_additives: []
    },
    {
        id: '17ae50bd-25bc-4f04-b6f3-3d9d10ea837c',
        name_en: 'Гасконский',
        name_kg: 'Гасконский',
        name_ru: 'Гасконский',
        description_en: '(Копчен.окорочка,огурцы,сыр голанд.,яйца,зел.лук,майонез)',
        description_kg: '(Копчен.окорочка,огурцы,сыр голанд.,яйца,зел.лук,майонез)',
        description_ru: '(Копчен.окорочка,огурцы,сыр голанд.,яйца,зел.лук,майонез)',
        price: 360,
        gram: '250',
        category_name: 'Салаты с майонезом',
        image: 'http://192.168.0.160:8000/media/dishes/8593c7b4a1f43f7c6beebdaa8f2a6cfd.png',
        available_additives: []
    },
    {
        id: 'd9519218-9ca3-4d55-9202-0849106134af',
        name_en: 'Ряба',
        name_kg: 'Ряба',
        name_ru: 'Ряба',
        description_en: '(Копченая утиная грудка,вешенки,яица,кур,сыр голандский,мойонез)',
        description_kg: '(Копченая утиная грудка,вешенки,яица,кур,сыр голандский,мойонез)',
        description_ru: '(Копченая утиная грудка,вешенки,яица,кур,сыр голандский,мойонез)',
        price: 360,
        gram: '250',
        category_name: 'Салаты с майонезом',
        image: 'http://192.168.0.160:8000/media/dishes/recipe_723d678e-210d-4cb9-adbf-87a6cbe8adb6.jpg',
        available_additives: []
    },
    {
        id: 'a3c30352-e1ad-4e29-86fa-9833471960cd',
        name_en: 'Мясо с грибами',
        name_kg: 'Мясо с грибами',
        name_ru: 'Мясо с грибами',
        description_en: '(Яйцо,мясо жар.,веш.жар. цезарь соус,парм.,)',
        description_kg: '(Яйцо,мясо жар.,веш.жар. цезарь соус,парм.,)',
        description_ru: '(Яйцо,мясо жар.,веш.жар. цезарь соус,парм.,)',
        price: 350,
        gram: '250',
        category_name: 'Салаты с майонезом',
        image: 'http://192.168.0.160:8000/media/dishes/p_O.jpg',
        available_additives: []
    },
    {
        id: 'f0357f11-539e-42a5-8058-efe72dc61e7d',
        name_en: 'Клеопатра',
        name_kg: 'Клеопатра',
        name_ru: 'Клеопатра',
        description_en: '(Отв.гов.,мясо,огурцы свежие,лук репчатый, яйцо отварное,горох,картофель)',
        description_kg: '(Отв.гов.,мясо,огурцы свежие,лук репчатый, яйцо отварное,горох,картофель)',
        description_ru: '(Отв.гов.,мясо,огурцы свежие,лук репчатый, яйцо отварное,горох,картофель)',
        price: 350,
        gram: '250',
        category_name: 'Салаты с майонезом',
        image: 'http://192.168.0.160:8000/media/dishes/salat-kleopatra-s-kuricei-i-krabovymi-palochkami_1433612208_1_max.jpg',
        available_additives: []
    },
    {
        id: '2433cb3f-0fce-4e6c-8824-c9716652aeaa',
        name_en: 'Цезарь с курицей',
        name_kg: 'Цезарь с курицей',
        name_ru: 'Цезарь с курицей',
        description_en: '(Айсберг,черри,кур.грудка,сыр парм.,соус цезарь)',
        description_kg: '(Айсберг,черри,кур.грудка,сыр парм.,соус цезарь)',
        description_ru: '(Айсберг,черри,кур.грудка,сыр парм.,соус цезарь)',
        price: 390,
        gram: '250',
        category_name: 'Салаты с майонезом',
        image: 'http://192.168.0.160:8000/media/dishes/IMG20211101150416-01.gif',
        available_additives: []
    },
    {
        id: '6e77f509-f00a-4b1b-84fc-ea84903a5121',
        name_en: 'Мужской каприз',
        name_kg: 'Мужской каприз',
        name_ru: 'Мужской каприз',
        description_en: '(Язык,свежие огурцы,марин.огурцы,омлет,огурцы черри зелень,сметана)',
        description_kg: '(Язык,свежие огурцы,марин.огурцы,омлет,огурцы черри зелень,сметана)',
        description_ru: '(Язык,свежие огурцы,марин.огурцы,омлет,огурцы черри зелень,сметана)',
        price: 360,
        gram: '250',
        category_name: 'Салаты с майонезом',
        image: 'http://192.168.0.160:8000/media/dishes/muzhskoj-kapriz-1.jpg',
        available_additives: []
    },
    {
        id: '52713489-7979-4c62-aee3-587f28a53ef7',
        name_en: 'Чиккенспайс ходолный',
        name_kg: 'Чиккенспайс ходолный',
        name_ru: 'Чиккенспайс ходолный',
        description_en: '(рис,  сливочный сыр, огурец, микс кунжут, имбирь, васаби, соевый соус)',
        description_kg: '(рис,  сливочный сыр, огурец, микс кунжут, имбирь, васаби, соевый соус)',
        description_ru: '(рис,  сливочный сыр, огурец, микс кунжут, имбирь, васаби, соевый соус)',
        price: 200,
        gram: '',
        category_name: 'Роллы',
        image: 'http://192.168.0.160:8000/media/dishes/photo.jpg',
        available_additives: []
    },
    {
        id: '2b3022bb-37ea-4957-b8ff-2f469735bfdf',
        name_en: 'Мозайка',
        name_kg: 'Мозайка',
        name_ru: 'Мозайка',
        description_en: '(Брокк.,коп груд.,цвет.кап.,пом,шпин.,кукур.,лук жарен.,перец болг.,сливки)',
        description_kg: '(Брокк.,коп груд.,цвет.кап.,пом,шпин.,кукур.,лук жарен.,перец болг.,сливки)',
        description_ru: '(Брокк.,коп груд.,цвет.кап.,пом,шпин.,кукур.,лук жарен.,перец болг.,сливки)',
        price: 360,
        gram: '250',
        category_name: 'Салаты с майонезом',
        image: 'http://192.168.0.160:8000/media/dishes/237_03_05_2013_419.jpg',
        available_additives: []
    },
    {
        id: '8329abc0-99cc-43ea-b266-c54045c12928',
        name_en: 'Аяши запеченный',
        name_kg: 'Аяши запеченный',
        name_ru: 'Аяши запеченный',
        description_en: '(рис, омлет, краб, майонез, сыр, гауда, имбирь, васаби, масаго, оранжевый, соевый соус)',
        description_kg: '(рис, омлет, краб, майонез, сыр, гауда, имбирь, васаби, масаго, оранжевый, соевый соус)',
        description_ru: '(рис, омлет, краб, майонез, сыр, гауда, имбирь, васаби, масаго, оранжевый, соевый соус)',
        price: 220,
        gram: '',
        category_name: 'Роллы',
        image: 'http://192.168.0.160:8000/media/dishes/80d636f6e75ca9be8976e222aee620ca.jpg',
        available_additives: []
    },
    {
        id: 'cdee43c3-56ea-487a-8d9c-c6f5cc58b7cc',
        name_en: 'Рыба форель с овощами',
        name_kg: 'Рыба форель с овощами',
        name_ru: 'Рыба форель с овощами',
        description_en: '',
        description_kg: '',
        description_ru: '',
        price: 340,
        gram: '',
        category_name: 'Шашлыки',
        image: 'http://192.168.0.160:8000/media/dishes/recept_10208_tmlj.jpg',
        available_additives: []
    },
    {
        id: 'd6722fca-84f5-4925-9866-e83b30e1b76d',
        name_en: 'Филодельфия',
        name_kg: 'Филодельфия',
        name_ru: 'Филодельфия',
        description_en: '(рис,  сливочный сыр, огурец, ласось, имбирь, васаби, соевый соус)',
        description_kg: '(рис,  сливочный сыр, огурец, ласось, имбирь, васаби, соевый соус)',
        description_ru: '(рис,  сливочный сыр, огурец, ласось, имбирь, васаби, соевый соус)',
        price: 230,
        gram: '',
        category_name: 'Роллы',
        image: 'http://192.168.0.160:8000/media/dishes/350D180D0BED0BBD0BB_D0A4D0B8D0BBD0B0D0B4D0B5D0BBD18CD184D0B8D18F.jpg',
        available_additives: []
    },
    {
        id: 'e8defec9-9021-4bb0-95f9-e3b54e6bfe9b',
        name_en: 'Картошка в тандыре',
        name_kg: 'Картошка в тандыре',
        name_ru: 'Картошка в тандыре',
        description_en: '',
        description_kg: '',
        description_ru: '',
        price: 160,
        gram: '',
        category_name: 'Шашлыки',
        image: 'http://192.168.0.160:8000/media/dishes/a9914c1c7a0706a7800808b7f1de6718.jpg',
        available_additives: []
    },
    {
        id: 'fb00bced-576d-496a-aa4e-27ba6a32a7f4',
        name_en: 'Хлебная корзина 10-12 чел.',
        name_kg: 'Хлебная корзина 10-12 чел.',
        name_ru: 'Хлебная корзина 10-12 чел.',
        description_en: '',
        description_kg: '',
        description_ru: '',
        price: 1200,
        gram: '',
        category_name: 'Мучные',
        image: 'http://192.168.0.160:8000/media/dishes/images_vsrXWtQ.jpg',
        available_additives: []
    },
    {
        id: '94fb076a-d17c-4f1c-a556-803f020e3c85',
        name_en: 'Пирамида',
        name_kg: 'Пирамида',
        name_ru: 'Пирамида',
        description_en: '',
        description_kg: '',
        description_ru: '',
        price: 310,
        gram: '',
        category_name: 'Мучные',
        image: 'http://192.168.0.160:8000/media/dishes/images_7Pl4WAr.jpg',
        available_additives: []
    },
    {
        id: '8fe6c9d7-18af-4d0c-b03a-d0c69c5ccb75',
        name_en: 'Боорсок',
        name_kg: 'Боорсок',
        name_ru: 'Боорсок',
        description_en: '',
        description_kg: '',
        description_ru: '',
        price: 310,
        gram: '',
        category_name: 'Мучные',
        image: 'http://192.168.0.160:8000/media/dishes/images_JsGSdeZ.jpg',
        available_additives: []
    },
    {
        id: '2d542685-48bd-461d-a380-445cc3f9fbc8',
        name_en: 'Ролл сырный запеченный',
        name_kg: 'Ролл сырный запеченный',
        name_ru: 'Ролл сырный запеченный',
        description_en: '(рис, нори, сливочный сыр,айсберг салат, кура су, майонез сыр пармизан, унаги соус, имбирь, васаби, соевый соус)',
        description_kg: '(рис, нори, сливочный сыр,айсберг салат, кура су, майонез сыр пармизан, унаги соус, имбирь, васаби, соевый соус)',
        description_ru: '(рис, нори, сливочный сыр,айсберг салат, кура су, майонез сыр пармизан, унаги соус, имбирь, васаби, соевый соус)',
        price: 220,
        gram: '',
        category_name: 'Роллы',
        image: 'http://192.168.0.160:8000/media/dishes/Fudziyama20losos-500x350.png',
        available_additives: []
    },
    {
        id: '5ef3ea70-7369-4ee1-9964-d9bcb3c7dc67',
        name_en: 'Элитный',
        name_kg: 'Элитный',
        name_ru: 'Элитный',
        description_en: '(Язык, памидоры, вешенки, перец, зелень, масло)',
        description_kg: '(Язык, памидоры, вешенки, перец, зелень, масло)',
        description_ru: '(Язык, памидоры, вешенки, перец, зелень, масло)',
        price: 370,
        gram: '250',
        category_name: 'Салаты с растительным маслом',
        image: 'http://192.168.0.160:8000/media/dishes/a5e825338e.jpg',
        available_additives: []
    },
    {
        id: 'fa1808a6-18b7-4884-b9b2-c41aba9ec6b3',
        name_en: 'Запеченный Флорида',
        name_kg: 'Запеченный Флорида',
        name_ru: 'Запеченный Флорида',
        description_en: '(рис, нори, слив сыр, омлет краб, яки соус, имбирь, васаби, соев соус)',
        description_kg: '(рис, нори, слив сыр, омлет краб, яки соус, имбирь, васаби, соев соус)',
        description_ru: '(рис, нори, слив сыр, омлет краб, яки соус, имбирь, васаби, соев соус)',
        price: 270,
        gram: '',
        category_name: 'Роллы',
        image: 'http://192.168.0.160:8000/media/dishes/117_gor.jpg',
        available_additives: []
    },
    {
        id: '8fb1dfc4-47e4-48da-bf19-2027ca2c7fbd',
        name_en: 'Калифорния темпура',
        name_kg: 'Калифорния темпура',
        name_ru: 'Калифорния темпура',
        description_en: '(рис, красн, масаго, огур, авокадо, унаги, имбирь, васаби, соев соус)',
        description_kg: '(рис, красн, масаго, огур, авокадо, унаги, имбирь, васаби, соев соус)',
        description_ru: '(рис, красн, масаго, огур, авокадо, унаги, имбирь, васаби, соев соус)',
        price: 270,
        gram: '',
        category_name: 'Роллы',
        image: 'http://192.168.0.160:8000/media/dishes/kaliforniya-tempura-rolly-zakazat-v-kafe-kustanas.jpg',
        available_additives: []
    },
    {
        id: '11735304-e129-407e-ae28-92e671340ee0',
        name_en: 'Салат из море продуктов',
        name_kg: 'Салат из море продуктов',
        name_ru: 'Салат из море продуктов',
        description_en: '(Криветки, кальмары, руккколы, лист салата, черри, масло)',
        description_kg: '(Криветки, кальмары, руккколы, лист салата, черри, масло)',
        description_ru: '(Криветки, кальмары, руккколы, лист салата, черри, масло)',
        price: 420,
        gram: '250',
        category_name: 'Салаты с растительным маслом',
        image: 'http://192.168.0.160:8000/media/dishes/93bfb56166152094b4ea082fb686a917.jpg',
        available_additives: []
    },
    {
        id: 'a76b9b4b-1b90-4a85-834b-43730abb7b65',
        name_en: 'Симона',
        name_kg: 'Симона',
        name_ru: 'Симона',
        description_en: '(спаржа, морк., перец болг. Зел., зелень специи)',
        description_kg: '(спаржа, морк., перец болг. Зел., зелень специи)',
        description_ru: '(спаржа, морк., перец болг. Зел., зелень специи)',
        price: 320,
        gram: '250',
        category_name: 'Салаты с растительным маслом',
        image: 'http://192.168.0.160:8000/media/dishes/images.jpg',
        available_additives: []
    },
    {
        id: '6227ac0d-c77d-4e9e-8891-9131ee0b4cbf',
        name_en: 'Свежый',
        name_kg: 'Свежый',
        name_ru: 'Свежый',
        description_en: '(огур, памид, лук, перец, болг, зелень)',
        description_kg: '(огур, памид, лук, перец, болг, зелень)',
        description_ru: '(огур, памид, лук, перец, болг, зелень)',
        price: 240,
        gram: '250',
        category_name: 'Салаты с растительным маслом',
        image: 'http://192.168.0.160:8000/media/dishes/9D977CE7-4542-48BE-88DA-4B8D10F0950B-1200x900.jpeg',
        available_additives: []
    },
    {
        id: 'c2650e38-ba02-4880-8aea-a2a2d757c737',
        name_en: 'Элита',
        name_kg: 'Элита',
        name_ru: 'Элита',
        description_en: '(Бон-филе, лоло, россо, руккола, шпинат, черри, соус бальзамик)',
        description_kg: '(Бон-филе, лоло, россо, руккола, шпинат, черри, соус бальзамик)',
        description_ru: '(Бон-филе, лоло, россо, руккола, шпинат, черри, соус бальзамик)',
        price: 390,
        gram: '250',
        category_name: 'Салаты с растительным маслом',
        image: 'http://192.168.0.160:8000/media/dishes/1677665307_food-pibig-info-p-salat-goryachii-s-govyadinoi-i-ovoshchami-18.jpg',
        available_additives: []
    },
    {
        id: '1ca05279-0f1a-434e-aac7-86f41629b554',
        name_en: 'Весенний',
        name_kg: 'Весенний',
        name_ru: 'Весенний',
        description_en: '(цветная капуста,брокколи, помидор, гов мясо, лист салата, кунжутное масло)',
        description_kg: '(цветная капуста,брокколи, помидор, гов мясо, лист салата, кунжутное масло)',
        description_ru: '(цветная капуста,брокколи, помидор, гов мясо, лист салата, кунжутное масло)',
        price: 350,
        gram: '250',
        category_name: 'Салаты с растительным маслом',
        image: 'http://192.168.0.160:8000/media/dishes/images_OaLiFeI.jpg',
        available_additives: []
    },
    {
        id: 'd504c509-0674-42b1-b7fa-9e70afd2c9fe',
        name_en: 'Моника',
        name_kg: 'Моника',
        name_ru: 'Моника',
        description_en: '(отв.Мясо,Помидор, чернослив, вяленный орахис, корнишон, болг перец зеленый лук, кукур, початки)',
        description_kg: '(отв.Мясо,Помидор, чернослив, вяленный орахис, корнишон, болг перец зеленый лук, кукур, початки)',
        description_ru: '(отв.Мясо,Помидор, чернослив, вяленный орахис, корнишон, болг перец зеленый лук, кукур, початки)',
        price: 350,
        gram: '250',
        category_name: 'Салаты с растительным маслом',
        image: 'http://192.168.0.160:8000/media/dishes/images_tY1ucqA.jpg',
        available_additives: []
    },
    {
        id: '66523da1-dc70-4047-9fed-986452b8c241',
        name_en: 'Адеми',
        name_kg: 'Адеми',
        name_ru: 'Адеми',
        description_en: '(мясо гов, помидор, кукурузные початки, корнишоны, зеленый горох, раст масло, омлет,опята марин)',
        description_kg: '(мясо гов, помидор, кукурузные початки, корнишоны, зеленый горох, раст масло, омлет,опята марин)',
        description_ru: '(мясо гов, помидор, кукурузные початки, корнишоны, зеленый горох, раст масло, омлет,опята марин)',
        price: 340,
        gram: '250',
        category_name: 'Салаты с растительным маслом',
        image: 'http://192.168.0.160:8000/media/dishes/images_mpY8h6y.jpg',
        available_additives: []
    },
    {
        id: 'c062c926-61a4-4078-b381-facf8088e0e8',
        name_en: 'Курица с Шампиньонами',
        name_kg: 'Курица с Шампиньонами',
        name_ru: 'Курица с Шампиньонами',
        description_en: '(отвар окорочка,шамп-марин, помидор, горчица, лист сал, растит-масло)',
        description_kg: '(отвар окорочка,шамп-марин, помидор, горчица, лист сал, растит-масло)',
        description_ru: '(отвар окорочка,шамп-марин, помидор, горчица, лист сал, растит-масло)',
        price: 330,
        gram: '250',
        category_name: 'Салаты с растительным маслом',
        image: 'http://192.168.0.160:8000/media/dishes/images_l8me6ef.jpg',
        available_additives: []
    },
    {
        id: 'bf3ffaf6-62bd-4365-b820-014e1e819afb',
        name_en: 'Греческий',
        name_kg: 'Греческий',
        name_ru: 'Греческий',
        description_en: '(огур., помид., олив., масл., перец болг.,лук шалот, зел.)',
        description_kg: '(огур., помид., олив., масл., перец болг.,лук шалот, зел.)',
        description_ru: '(огур., помид., олив., масл., перец болг.,лук шалот, зел.)',
        price: 350,
        gram: '250',
        category_name: 'Салаты с растительным маслом',
        image: 'http://192.168.0.160:8000/media/dishes/images_EBmM3ej.jpg',
        available_additives: []
    },
    {
        id: '45de53cd-4213-4439-88dc-477da6a215f2',
        name_en: 'Дымдама',
        name_kg: 'Дымдама',
        name_ru: 'Дымдама',
        description_en: '',
        description_kg: '',
        description_ru: '',
        price: 1550,
        gram: '1000',
        category_name: 'Общие блюда',
        image: 'http://192.168.0.160:8000/media/dishes/images_NPKdwez.jpg',
        available_additives: []
    },
    {
        id: '005ec12f-60d3-4848-b3aa-607cb205776e',
        name_en: 'Пирожок',
        name_kg: 'Пирожок',
        name_ru: 'Пирожок',
        description_en: '',
        description_kg: '',
        description_ru: '',
        price: 1450,
        gram: '1000',
        category_name: 'Общие блюда',
        image: 'http://192.168.0.160:8000/media/dishes/images_5aYnQoI.jpg',
        available_additives: []
    },
    {
        id: 'c2364923-41dd-402c-9c9b-0c5d66c8e8e5',
        name_en: 'Пирожок из курицы',
        name_kg: 'Пирожок из курицы',
        name_ru: 'Пирожок из курицы',
        description_en: '',
        description_kg: '',
        description_ru: '',
        price: 1700,
        gram: '1500',
        category_name: 'Общие блюда',
        image: 'http://192.168.0.160:8000/media/dishes/images_zdbgnhV.jpg',
        available_additives: []
    },
    {
        id: '718bfde8-ea07-4c2e-aa6d-ca5d856a1958',
        name_en: 'Пирожок спец заказ',
        name_kg: 'Пирожок спец заказ',
        name_ru: 'Пирожок спец заказ',
        description_en: '',
        description_kg: '',
        description_ru: '',
        price: 2800,
        gram: '2000',
        category_name: 'Общие блюда',
        image: 'http://192.168.0.160:8000/media/dishes/135559.png',
        available_additives: []
    },
    {
        id: '885e2e46-f363-4999-8581-41b868cd253e',
        name_en: 'Ассорти улуу тоо на 10 чел',
        name_kg: 'Ассорти улуу тоо на 10 чел',
        name_ru: 'Ассорти улуу тоо на 10 чел',
        description_en: '(бар голень, баран стейк, тибон стейк, цыпленок табака, рибай стейк, бар ребрышки, ньюйорк стейк, кур крылышки, кур голень,перепелка, переп яицо, овощи на гриле)',
        description_kg: '(бар голень, баран стейк, тибон стейк, цыпленок табака, рибай стейк, бар ребрышки, ньюйорк стейк, кур крылышки, кур голень,перепелка, переп яицо, овощи на гриле)',
        description_ru: '(бар голень, баран стейк, тибон стейк, цыпленок табака, рибай стейк, бар ребрышки, ньюйорк стейк, кур крылышки, кур голень,перепелка, переп яицо, овощи на гриле)',
        price: 6000,
        gram: '5500',
        category_name: 'Общие блюда',
        image: 'http://192.168.0.160:8000/media/dishes/images_i1c6gJC.jpg',
        available_additives: []
    },
    {
        id: '5be1cdee-bc11-4b37-84c7-cbe7fc226621',
        name_en: 'Мясной сет по кавказский на 7 персон',
        name_kg: 'Мясной сет по кавказский на 7 персон',
        name_ru: 'Мясной сет по кавказский на 7 персон',
        description_en: '(7 ребрышек из баранины, 7 медальонов, 7 стейков из антрекот, 7 крылышек по арабский, сырно-овощной рулет из лаваша, соус)',
        description_kg: '(7 ребрышек из баранины, 7 медальонов, 7 стейков из антрекот, 7 крылышек по арабский, сырно-овощной рулет из лаваша, соус)',
        description_ru: '(7 ребрышек из баранины, 7 медальонов, 7 стейков из антрекот, 7 крылышек по арабский, сырно-овощной рулет из лаваша, соус)',
        price: 4000,
        gram: '',
        category_name: 'Общие блюда',
        image: 'http://192.168.0.160:8000/media/dishes/images_TCTEP3D.jpg',
        available_additives: []
    },
    {
        id: '16319cd7-0e7a-426c-be53-625077047a02',
        name_en: 'Запеченная баранья ножка в тесте',
        name_kg: 'Запеченная баранья ножка в тесте',
        name_ru: 'Запеченная баранья ножка в тесте',
        description_en: '(овощи на гриле, овощи припушенные с изюмом)',
        description_kg: '(овощи на гриле, овощи припушенные с изюмом)',
        description_ru: '(овощи на гриле, овощи припушенные с изюмом)',
        price: 5000,
        gram: '4000',
        category_name: 'Общие блюда',
        image: 'http://192.168.0.160:8000/media/dishes/images_oyQhff1.jpg',
        available_additives: []
    },
    {
        id: '23d8fec8-454d-4a1f-a7cf-f9a60bf991d3',
        name_en: 'Плов фирменный',
        name_kg: 'Плов фирменный',
        name_ru: 'Плов фирменный',
        description_en: '(ноокот, изюм, перепилиные яица)',
        description_kg: '(ноокот, изюм, перепилиные яица)',
        description_ru: '(ноокот, изюм, перепилиные яица)',
        price: 2200,
        gram: '1000',
        category_name: 'Общие блюда',
        image: 'http://192.168.0.160:8000/media/dishes/images_Sie2Vc9.jpg',
        available_additives: []
    },
    {
        id: '8412ec80-b2a0-41ae-a958-8e30881b3d67',
        name_en: 'Восточная сказка',
        name_kg: 'Восточная сказка',
        name_ru: 'Восточная сказка',
        description_en: '(бар голень, бар ребрышки, кур крылышки, перепилка, овощина гриле)',
        description_kg: '(бар голень, бар ребрышки, кур крылышки, перепилка, овощина гриле)',
        description_ru: '(бар голень, бар ребрышки, кур крылышки, перепилка, овощина гриле)',
        price: 4600,
        gram: '4000',
        category_name: 'Общие блюда',
        image: 'http://192.168.0.160:8000/media/dishes/images_frH3SIP.jpg',
        available_additives: []
    },
    {
        id: '687f82c0-11b9-474d-bc2b-0f300923f985',
        name_en: 'Беш бармак',
        name_kg: 'Беш бармак',
        name_ru: 'Беш бармак',
        description_en: '',
        description_kg: '',
        description_ru: '',
        price: 1950,
        gram: '1000',
        category_name: 'Общие блюда',
        image: 'http://192.168.0.160:8000/media/dishes/images_K6tArEe.jpg',
        available_additives: []
    },
    {
        id: '511ed6eb-24e0-4283-8ad3-2bf195e1db17',
        name_en: 'Мясное ассорти (на 10 чел.)',
        name_kg: 'Мясное ассорти (на 10 чел.)',
        name_ru: 'Мясное ассорти (на 10 чел.)',
        description_en: '(тибон стейк, рибай стейк, бар ребрышки, бон филе, кур крылышки, утиная грудка, овощи на гриле)',
        description_kg: '(тибон стейк, рибай стейк, бар ребрышки, бон филе, кур крылышки, утиная грудка, овощи на гриле)',
        description_ru: '(тибон стейк, рибай стейк, бар ребрышки, бон филе, кур крылышки, утиная грудка, овощи на гриле)',
        price: 6200,
        gram: '5000',
        category_name: 'Общие блюда',
        image: 'http://192.168.0.160:8000/media/dishes/images_74qBtt8.jpg',
        available_additives: []
    },
    {
        id: '67ebf557-b6f9-46d4-942a-16b7fa0c59a1',
        name_en: 'Курица запеченная',
        name_kg: 'Курица запеченная',
        name_ru: 'Курица запеченная',
        description_en: '',
        description_kg: '',
        description_ru: '',
        price: 1050,
        gram: '',
        category_name: 'Банкетные блюда',
        image: 'http://192.168.0.160:8000/media/dishes/images_UEa2arS.jpg',
        available_additives: []
    },
    {
        id: 'bf0041cd-a1e7-4013-b7d9-1ab8ec4abf4c',
        name_en: 'Форель',
        name_kg: 'Форель',
        name_ru: 'Форель',
        description_en: '',
        description_kg: '',
        description_ru: '',
        price: 1550,
        gram: '',
        category_name: 'Банкетные блюда',
        image: 'http://192.168.0.160:8000/media/dishes/images_43XQ5Wa.jpg',
        available_additives: []
    },
    {
        id: '75998cc2-6a86-4077-946e-c8f334885477',
        name_en: 'Суп улуу тоо',
        name_kg: 'Суп улуу тоо',
        name_ru: 'Суп улуу тоо',
        description_en: '',
        description_kg: '',
        description_ru: '',
        price: 240,
        gram: '',
        category_name: 'Первые блюда',
        image: 'http://192.168.0.160:8000/media/dishes/images_ldBEeMp.jpg',
        available_additives: []
    },
    {
        id: '8da7ca18-5ae2-4bef-add0-1a158e2b2690',
        name_en: 'Кок тал из форели',
        name_kg: 'Кок тал из форели',
        name_ru: 'Кок тал из форели',
        description_en: '',
        description_kg: '',
        description_ru: '',
        price: 1900,
        gram: '',
        category_name: 'Банкетные блюда',
        image: 'http://192.168.0.160:8000/media/dishes/images_2rn4iUp.jpg',
        available_additives: []
    },
    {
        id: 'ea95b04d-3bf6-446f-bb8f-623d61be2b17',
        name_en: 'Горбуша',
        name_kg: 'Горбуша',
        name_ru: 'Горбуша',
        description_en: '',
        description_kg: '',
        description_ru: '',
        price: 1400,
        gram: '',
        category_name: 'Банкетные блюда',
        image: 'http://192.168.0.160:8000/media/dishes/images_2I7G9VD.jpg',
        available_additives: []
    },
    {
        id: '3c274473-8f06-4e99-8054-e761fbc95f18',
        name_en: 'Суп от шефа',
        name_kg: 'Суп от шефа',
        name_ru: 'Суп от шефа',
        description_en: '',
        description_kg: '',
        description_ru: '',
        price: 230,
        gram: '',
        category_name: 'Первые блюда',
        image: 'http://192.168.0.160:8000/media/dishes/images_plbZoHp.jpg',
        available_additives: []
    },
    {
        id: 'fee0d8e5-1ed4-4959-8f60-bc15d57f0a95',
        name_en: 'Шорпо баранина',
        name_kg: 'Шорпо баранина',
        name_ru: 'Шорпо баранина',
        description_en: '',
        description_kg: '',
        description_ru: '',
        price: 260,
        gram: '',
        category_name: 'Первые блюда',
        image: 'http://192.168.0.160:8000/media/dishes/images_a5sSSnr.jpg',
        available_additives: []
    },
    {
        id: '79e28f9c-de42-45dd-8adc-36785f75a9dd',
        name_en: 'Чечевичный',
        name_kg: 'Чечевичный',
        name_ru: 'Чечевичный',
        description_en: '',
        description_kg: '',
        description_ru: '',
        price: 160,
        gram: '',
        category_name: 'Первые блюда',
        image: 'http://192.168.0.160:8000/media/dishes/images_pzjS1Ki.jpg',
        available_additives: []
    },
    {
        id: '289d36ca-4593-4cc9-b6c1-0862a9fcd9b8',
        name_en: 'Суп восточный',
        name_kg: 'Суп восточный',
        name_ru: 'Суп восточный',
        description_en: '',
        description_kg: '',
        description_ru: '',
        price: 210,
        gram: '',
        category_name: 'Первые блюда',
        image: 'http://192.168.0.160:8000/media/dishes/images_sYDtzye.jpg',
        available_additives: []
    },
    {
        id: '51a86974-dc1d-474c-a0fc-b6150651a006',
        name_en: 'Грибной крем суп',
        name_kg: 'Грибной крем суп',
        name_ru: 'Грибной крем суп',
        description_en: '',
        description_kg: '',
        description_ru: '',
        price: 160,
        gram: '',
        category_name: 'Первые блюда',
        image: 'http://192.168.0.160:8000/media/dishes/images_ecDD6px.jpg',
        available_additives: []
    },
    {
        id: 'a99fd3d1-005d-4b98-8971-f9952d2226a3',
        name_en: 'Шорпо говядина',
        name_kg: 'Шорпо говядина',
        name_ru: 'Шорпо говядина',
        description_en: '',
        description_kg: '',
        description_ru: '',
        price: 260,
        gram: '',
        category_name: 'Первые блюда',
        image: 'http://192.168.0.160:8000/media/dishes/images_GHokPzQ.jpg',
        available_additives: []
    },
    {
        id: 'b0734f78-704e-45d0-be42-7eb185cb949d',
        name_en: 'Фрикадельки',
        name_kg: 'Фрикадельки',
        name_ru: 'Фрикадельки',
        description_en: '',
        description_kg: '',
        description_ru: '',
        price: 220,
        gram: '',
        category_name: 'Первые блюда',
        image: 'http://192.168.0.160:8000/media/dishes/images_O7FHvli.jpg',
        available_additives: []
    },
    {
        id: 'ddb9ed85-7797-4e03-a38b-40c1fde50c3d',
        name_en: 'Суп озгочо',
        name_kg: 'Суп озгочо',
        name_ru: 'Суп озгочо',
        description_en: '',
        description_kg: '',
        description_ru: '',
        price: 200,
        gram: '',
        category_name: 'Первые блюда',
        image: 'http://192.168.0.160:8000/media/dishes/images_s5wZzWF.jpg',
        available_additives: []
    },
    {
        id: '71ecf4bd-51dc-4232-90dc-48b848cfdf84',
        name_en: 'Мампар',
        name_kg: 'Мампар',
        name_ru: 'Мампар',
        description_en: '',
        description_kg: '',
        description_ru: '',
        price: 200,
        gram: '',
        category_name: 'Первые блюда',
        image: 'http://192.168.0.160:8000/media/dishes/images_n9iHIi5.jpg',
        available_additives: []
    },
    {
        id: '5da9946d-fc0c-404c-9d63-0bedcd517572',
        name_en: 'Жаренные баклажаны',
        name_kg: 'Жаренные баклажаны',
        name_ru: 'Жаренные баклажаны',
        description_en: '(баклажаны жаренные, помидоры, соус, зелень)',
        description_kg: '(баклажаны жаренные, помидоры, соус, зелень)',
        description_ru: '(баклажаны жаренные, помидоры, соус, зелень)',
        price: 340,
        gram: '250',
        category_name: 'Острые салаты (с соевым соусом)',
        image: 'http://192.168.0.160:8000/media/dishes/images_JqbWiCF.jpg',
        available_additives: []
    },
    {
        id: '5884b1d2-e33e-4251-b827-2e817d3ec9e2',
        name_en: 'Бамбук',
        name_kg: 'Бамбук',
        name_ru: 'Бамбук',
        description_en: '(Бас., шпин.,бамб., черри, морк,слад. Чил.Соус)',
        description_kg: '(Бас., шпин.,бамб., черри, морк,слад. Чил.Соус)',
        description_ru: '(Бас., шпин.,бамб., черри, морк,слад. Чил.Соус)',
        price: 360,
        gram: '250',
        category_name: 'Острые салаты (с соевым соусом)',
        image: 'http://192.168.0.160:8000/media/dishes/images_mkzyZcJ.jpg',
        available_additives: []
    },
    {
        id: '4005bf84-857c-4f61-9979-736c914fceb5',
        name_en: 'Фунчеза',
        name_kg: 'Фунчеза',
        name_ru: 'Фунчеза',
        description_en: '(корей. Фунчеза, пер. Болг., мясо, лук, морковь, сельдерей)',
        description_kg: '(корей. Фунчеза, пер. Болг., мясо, лук, морковь, сельдерей)',
        description_ru: '(корей. Фунчеза, пер. Болг., мясо, лук, морковь, сельдерей)',
        price: 310,
        gram: '250',
        category_name: 'Острые салаты (с соевым соусом)',
        image: 'http://192.168.0.160:8000/media/dishes/images_jBbPFse.jpg',
        available_additives: []
    },
    {
        id: 'fee08f81-277a-46d4-97c0-441b2eddf8a6',
        name_en: 'Салат с языком',
        name_kg: 'Салат с языком',
        name_ru: 'Салат с языком',
        description_en: '(отварной язык, огурцы, помидор, лук, кинза, соевый соус)',
        description_kg: '(отварной язык, огурцы, помидор, лук, кинза, соевый соус)',
        description_ru: '(отварной язык, огурцы, помидор, лук, кинза, соевый соус)',
        price: 360,
        gram: '250',
        category_name: 'Острые салаты (с соевым соусом)',
        image: 'http://192.168.0.160:8000/media/dishes/images_s3ZKsKB.jpg',
        available_additives: []
    },
    {
        id: 'db429f58-9423-465e-8dc1-3a6eae624b6b',
        name_en: 'Хоргос',
        name_kg: 'Хоргос',
        name_ru: 'Хоргос',
        description_en: '(мясо гов., перец, огур. Св., лук, соевый соус)',
        description_kg: '(мясо гов., перец, огур. Св., лук, соевый соус)',
        description_ru: '(мясо гов., перец, огур. Св., лук, соевый соус)',
        price: 370,
        gram: '250',
        category_name: 'Острые салаты (с соевым соусом)',
        image: 'http://192.168.0.160:8000/media/dishes/images_W3LrRW3.jpg',
        available_additives: []
    },
    {
        id: '9f84e7a6-02c9-4aa8-afc4-7691d5b66789',
        name_en: 'Пицца куриная',
        name_kg: 'Пицца куриная',
        name_ru: 'Пицца куриная',
        description_en: '',
        description_kg: '',
        description_ru: '',
        price: 400,
        gram: '400',
        category_name: 'Детское меню',
        image: 'http://192.168.0.160:8000/media/dishes/images_IL7ypuE.jpg',
        available_additives: []
    },
    {
        id: 'e407c7b9-1f60-49ba-a9da-8ba6b6a7d306',
        name_en: 'Какаду',
        name_kg: 'Какаду',
        name_ru: 'Какаду',
        description_en: '(жар. Гов. Мясо, морковь, огурцы, стручковый фасоль, болг. Перец).',
        description_kg: '(жар. Гов. Мясо, морковь, огурцы, стручковый фасоль, болг. Перец).',
        description_ru: '(жар. Гов. Мясо, морковь, огурцы, стручковый фасоль, болг. Перец).',
        price: 360,
        gram: '250',
        category_name: 'Острые салаты (с соевым соусом)',
        image: 'http://192.168.0.160:8000/media/dishes/images_3yFx4fw.jpg',
        available_additives: []
    },
    {
        id: 'b095f285-b930-4caa-bbee-90370fe45f21',
        name_en: 'Улуу тоо фирменное',
        name_kg: 'Улуу тоо фирменное',
        name_ru: 'Улуу тоо фирменное',
        description_en: '(жареные мясо, тефтели, фаршированное мясо в яйцо, овощи.Шашлыки,капусте, тыква,)',
        description_kg: '(жареные мясо, тефтели, фаршированное мясо в яйцо, овощи.Шашлыки,капусте, тыква,)',
        description_ru: '(жареные мясо, тефтели, фаршированное мясо в яйцо, овощи.Шашлыки,капусте, тыква,)',
        price: 3700,
        gram: '2000',
        category_name: 'Общие блюда',
        image: 'http://192.168.0.160:8000/media/dishes/images_j1GBxbI.jpg',
        available_additives: []
    },
    {
        id: 'c5e97794-47b1-428d-8a37-5d2b98740362',
        name_en: 'Марокканский чай',
        name_kg: 'Марокканский чай',
        name_ru: 'Марокканский чай',
        description_en: '',
        description_kg: '',
        description_ru: '',
        price: 190,
        gram: '',
        category_name: 'Горячие напитки',
        image: 'http://192.168.0.160:8000/media/dishes/recept_6752_mo3z.jpg',
        available_additives: []
    },
    {
        id: 'b754065c-a683-483d-b461-6985dc067c67',
        name_en: 'Пицца маргарита',
        name_kg: 'Пицца маргарита',
        name_ru: 'Пицца маргарита',
        description_en: '',
        description_kg: '',
        description_ru: '',
        price: 400,
        gram: '400',
        category_name: 'Детское меню',
        image: 'http://192.168.0.160:8000/media/dishes/images_igFc28p.jpg',
        available_additives: []
    },
    {
        id: '7a9708a1-fb2d-44d7-9c32-3e536deb4a83',
        name_en: 'Чай черный',
        name_kg: 'Чай черный',
        name_ru: 'Чай черный',
        description_en: '',
        description_kg: '',
        description_ru: '',
        price: 55,
        gram: '',
        category_name: 'Горячие напитки',
        image: 'http://192.168.0.160:8000/media/dishes/1.jpg',
        available_additives: []
    },
    {
        id: '1fb2bf5d-d858-4935-ae53-f3ed4351a982',
        name_en: 'Крылышки 3шт',
        name_kg: 'Крылышки 3шт',
        name_ru: 'Крылышки 3шт',
        description_en: '',
        description_kg: '',
        description_ru: '',
        price: 170,
        gram: '',
        category_name: 'Детское меню',
        image: 'http://192.168.0.160:8000/media/dishes/images_NjVPP25.jpg',
        available_additives: []
    },
    {
        id: '009eeae7-cefa-4ce1-86b5-fbdf956589f3',
        name_en: 'Сосиски 3шт',
        name_kg: 'Сосиски 3шт',
        name_ru: 'Сосиски 3шт',
        description_en: '',
        description_kg: '',
        description_ru: '',
        price: 160,
        gram: '',
        category_name: 'Детское меню',
        image: 'http://192.168.0.160:8000/media/dishes/images_liczFku.jpg',
        available_additives: []
    },
    {
        id: '1284443f-df05-4124-802a-6712fd876b4a',
        name_en: 'Пицца мясная',
        name_kg: 'Пицца мясная',
        name_ru: 'Пицца мясная',
        description_en: '',
        description_kg: '',
        description_ru: '',
        price: 400,
        gram: '400',
        category_name: 'Детское меню',
        image: 'http://192.168.0.160:8000/media/dishes/images_ouiu1P1.jpg',
        available_additives: []
    },
    {
        id: 'b7059e69-553a-4eae-88b1-c481aba995dc',
        name_en: 'Жасминовый чай',
        name_kg: 'Жасминовый чай',
        name_ru: 'Жасминовый чай',
        description_en: '',
        description_kg: '',
        description_ru: '',
        price: 55,
        gram: '',
        category_name: 'Горячие напитки',
        image: 'http://192.168.0.160:8000/media/dishes/4ece97c13b4e552f270aee345ec4ca1d.png',
        available_additives: []
    },
    {
        id: '57aee568-39bb-43bb-a417-750a88fbb2b6',
        name_en: 'Пицца пепперони',
        name_kg: 'Пицца пепперони',
        name_ru: 'Пицца пепперони',
        description_en: '',
        description_kg: '',
        description_ru: '',
        price: 410,
        gram: '400',
        category_name: 'Детское меню',
        image: 'http://192.168.0.160:8000/media/dishes/images_Bi0xrjD.jpg',
        available_additives: []
    },
    {
        id: '05373542-1151-4c64-85de-8e809a73a5a1',
        name_en: 'Чай зеленый',
        name_kg: 'Чай зеленый',
        name_ru: 'Чай зеленый',
        description_en: '',
        description_kg: '',
        description_ru: '',
        price: 55,
        gram: '',
        category_name: 'Горячие напитки',
        image: 'http://192.168.0.160:8000/media/dishes/images_0y35gAT.jpg',
        available_additives: []
    },
    {
        id: '919b2fdd-e85a-4474-b19c-a9cc9aa89709',
        name_en: 'Черная смородина с\nМандарином',
        name_kg: 'Черная смородина с\nМандарином',
        name_ru: 'Черная смородина с\nМандарином',
        description_en: '',
        description_kg: '',
        description_ru: '',
        price: 170,
        gram: '',
        category_name: 'Горячие напитки',
        image: 'http://192.168.0.160:8000/media/dishes/kompot-iz-chernoi-smorodini-s-apelsinom-770x513.jpg',
        available_additives: []
    },
    {
        id: '1a718181-3413-43a2-a471-1f42e5697a3c',
        name_en: 'Чай с бергамотом',
        name_kg: 'Чай с бергамотом',
        name_ru: 'Чай с бергамотом',
        description_en: '',
        description_kg: '',
        description_ru: '',
        price: 150,
        gram: '',
        category_name: 'Горячие напитки',
        image: 'http://192.168.0.160:8000/media/dishes/Oh2A6NsE6L1rQoCW.jpg',
        available_additives: []
    },
    {
        id: 'e0285a43-806a-4b88-8b91-ab6c43e89cc9',
        name_en: 'Ягодный чай',
        name_kg: 'Ягодный чай',
        name_ru: 'Ягодный чай',
        description_en: '',
        description_kg: '',
        description_ru: '',
        price: 240,
        gram: '',
        category_name: 'Горячие напитки',
        image: 'http://192.168.0.160:8000/media/dishes/shutterstock_294681614_1579264997-e1579265029512-1280x640.jpg',
        available_additives: []
    },
    {
        id: 'a46e72cb-37e1-49ad-93b4-0c7f19bbe22e',
        name_en: 'Чай с мятой',
        name_kg: 'Чай с мятой',
        name_ru: 'Чай с мятой',
        description_en: '',
        description_kg: '',
        description_ru: '',
        price: 100,
        gram: '',
        category_name: 'Горячие напитки',
        image: 'http://192.168.0.160:8000/media/dishes/df8ba5775fb4e03d07187221cb9102a6.jpg',
        available_additives: []
    },
    {
        id: '9afecb71-47c8-4e3c-b8fc-9aa764275bf2',
        name_en: 'Имбирный с\nМалиной',
        name_kg: 'Имбирный с\nМалиной',
        name_ru: 'Имбирный с\nМалиной',
        description_en: '',
        description_kg: '',
        description_ru: '',
        price: 190,
        gram: '',
        category_name: 'Горячие напитки',
        image: 'http://192.168.0.160:8000/media/dishes/Tea-3.jpg',
        available_additives: []
    },
    {
        id: '84c65f3d-3479-4fec-af8c-e60609c23efd',
        name_en: 'Чай с молоком',
        name_kg: 'Чай с молоком',
        name_ru: 'Чай с молоком',
        description_en: '',
        description_kg: '',
        description_ru: '',
        price: 150,
        gram: '',
        category_name: 'Горячие напитки',
        image: 'http://192.168.0.160:8000/media/dishes/chai-s-molokom_1567196540_6_max.jpg',
        available_additives: []
    },
    {
        id: 'f2abc4db-4d9e-4878-a6e6-d2267f82174c',
        name_en: 'Апельсин с\nТимьяном',
        name_kg: 'Апельсин с\nТимьяном',
        name_ru: 'Апельсин с\nТимьяном',
        description_en: '',
        description_kg: '',
        description_ru: '',
        price: 170,
        gram: '',
        category_name: 'Горячие напитки',
        image: 'http://192.168.0.160:8000/media/dishes/thyme_orangeade_web-595x394.jpg',
        available_additives: []
    },
    {
        id: 'b5a1cf9c-8d79-4ec1-914d-9fa4c4b6bc4d',
        name_en: 'Мэй гуй че',
        name_kg: 'Мэй гуй че',
        name_ru: 'Мэй гуй че',
        description_en: '',
        description_kg: '',
        description_ru: '',
        price: 160,
        gram: '',
        category_name: 'Горячие напитки',
        image: 'http://192.168.0.160:8000/media/dishes/2014_12_01_04_002.jpg',
        available_additives: []
    },
    {
        id: 'aa1f872c-0caa-4779-ab6f-48fded040cdf',
        name_en: 'Молочный улун',
        name_kg: 'Молочный улун',
        name_ru: 'Молочный улун',
        description_en: '',
        description_kg: '',
        description_ru: '',
        price: 150,
        gram: '',
        category_name: 'Горячие напитки',
        image: 'http://192.168.0.160:8000/media/dishes/01.jpeg',
        available_additives: []
    },
    {
        id: '2a7a6494-94c3-4134-984a-9a3c1c8a02e6',
        name_en: 'Клюква с медом',
        name_kg: 'Клюква с медом',
        name_ru: 'Клюква с медом',
        description_en: '',
        description_kg: '',
        description_ru: '',
        price: 190,
        gram: '',
        category_name: 'Горячие напитки',
        image: 'http://192.168.0.160:8000/media/dishes/kofe-345.jpg',
        available_additives: []
    },
    {
        id: '98dad758-e904-467b-8db8-aa7e024c9ed7',
        name_en: 'Облепиха с\nГрушей',
        name_kg: 'Облепиха с\nГрушей',
        name_ru: 'Облепиха с\nГрушей',
        description_en: '',
        description_kg: '',
        description_ru: '',
        price: 240,
        gram: '',
        category_name: 'Горячие напитки',
        image: 'http://192.168.0.160:8000/media/dishes/b9b8d872.jpg',
        available_additives: []
    },
    {
        id: '8aae8c18-992c-4b64-9a51-7033976f59d2',
        name_en: 'Смородина с медом',
        name_kg: 'Смородина с медом',
        name_ru: 'Смородина с медом',
        description_en: '',
        description_kg: '',
        description_ru: '',
        price: 160,
        gram: '',
        category_name: 'Горячие напитки',
        image: 'http://192.168.0.160:8000/media/dishes/1576611116_img_7760jj.jpg',
        available_additives: []
    },
    {
        id: '000997df-24d7-40b2-91bf-d88c42caa420',
        name_en: 'Ассорти шашлык',
        name_kg: 'Ассорти шашлык',
        name_ru: 'Ассорти шашлык',
        description_en: '',
        description_kg: '',
        description_ru: '',
        price: 2200,
        gram: '1900',
        category_name: 'Шашлыки',
        image: 'http://192.168.0.160:8000/media/dishes/assorti-iz-shashlyikov-na-5-person-4-1-scaled-2-600x400.jpg',
        available_additives: []
    },
    {
        id: 'c21a2455-b759-46f4-94c1-35dc82be13a7',
        name_en: 'Согревающий',
        name_kg: 'Согревающий',
        name_ru: 'Согревающий',
        description_en: '',
        description_kg: '',
        description_ru: '',
        price: 260,
        gram: '',
        category_name: 'Горячие напитки',
        image: 'http://192.168.0.160:8000/media/dishes/e90ee79c7be7568575dda70ba007d1bb.jpg',
        available_additives: []
    },
    {
        id: '56a8b852-f45f-4b7c-8f5e-76e1eeefedb0',
        name_en: 'Кола',
        name_kg: 'Кола',
        name_ru: 'Кола',
        description_en: '',
        description_kg: '',
        description_ru: '',
        price: 120,
        gram: '1000',
        category_name: 'Холдные',
        image: 'http://192.168.0.160:8000/media/dishes/napitok-sierra-coca-cola-1-l-gazirovannyj-121-1.webp',
        available_additives: []
    },
    {
        id: 'b5c2b8ee-0504-4bd4-b679-acf3bb774c4b',
        name_en: 'Баранина филе',
        name_kg: 'Баранина филе',
        name_ru: 'Баранина филе',
        description_en: '',
        description_kg: '',
        description_ru: '',
        price: 350,
        gram: '',
        category_name: 'Шашлыки',
        image: 'http://192.168.0.160:8000/media/dishes/maxresdefault_WSCQGCY.jpg',
        available_additives: []
    },
    {
        id: '85ba235c-2194-4213-90dc-6944256d9cc9',
        name_en: 'Фанта',
        name_kg: 'Фанта',
        name_ru: 'Фанта',
        description_en: '',
        description_kg: '',
        description_ru: '',
        price: 120,
        gram: '1000',
        category_name: 'Холдные',
        image: 'http://192.168.0.160:8000/media/dishes/Fanta-1L.jpeg',
        available_additives: []
    },
    {
        id: 'b33917f3-d5fe-41bb-b620-d907613914a7',
        name_en: 'Спрайт',
        name_kg: 'Спрайт',
        name_ru: 'Спрайт',
        description_en: '',
        description_kg: '',
        description_ru: '',
        price: 120,
        gram: '1000',
        category_name: 'Холдные',
        image: 'http://192.168.0.160:8000/media/dishes/20797-napitok_sprite_1_l.jpg',
        available_additives: []
    },
    {
        id: '2176f892-6cf8-47da-9b97-95bea246554e',
        name_en: 'Бараньи ребра',
        name_kg: 'Бараньи ребра',
        name_ru: 'Бараньи ребра',
        description_en: '',
        description_kg: '',
        description_ru: '',
        price: 350,
        gram: '',
        category_name: 'Шашлыки',
        image: 'http://192.168.0.160:8000/media/dishes/bfedaf1b.jpg',
        available_additives: []
    },
    {
        id: 'abfcfee7-0347-4595-80af-1700741d90f1',
        name_en: 'Компот',
        name_kg: 'Компот',
        name_ru: 'Компот',
        description_en: '',
        description_kg: '',
        description_ru: '',
        price: 80,
        gram: '1000',
        category_name: 'Холдные',
        image: 'http://192.168.0.160:8000/media/dishes/kompot-iz-chereshni_siteweb.jpg',
        available_additives: []
    },
    {
        id: '540e6666-3391-42d4-8e83-a4af2170b95b',
        name_en: 'Вода с газом',
        name_kg: 'Вода с газом',
        name_ru: 'Вода с газом',
        description_en: '',
        description_kg: '',
        description_ru: '',
        price: 40,
        gram: '1000',
        category_name: 'Холдные',
        image: 'http://192.168.0.160:8000/media/dishes/6639447f16503569648ad733590451f1.jpg',
        available_additives: []
    },
    {
        id: 'cd125814-5a52-4916-9fb2-6bbae1c71ea1',
        name_en: 'Говядина филе',
        name_kg: 'Говядина филе',
        name_ru: 'Говядина филе',
        description_en: '',
        description_kg: '',
        description_ru: '',
        price: 350,
        gram: '',
        category_name: 'Шашлыки',
        image: 'http://192.168.0.160:8000/media/dishes/images_CPvYE3K.jpg',
        available_additives: []
    },
    {
        id: '4e9d8a77-e72c-41aa-adb6-adab4ab570b7',
        name_en: 'Вода без газом',
        name_kg: 'Вода без газом',
        name_ru: 'Вода без газом',
        description_en: '',
        description_kg: '',
        description_ru: '',
        price: 40,
        gram: '1000',
        category_name: 'Холдные',
        image: 'http://192.168.0.160:8000/media/dishes/6639447f16503569648ad733590451f1_Sb6BdHd.jpg',
        available_additives: []
    },
    {
        id: '4b436040-6a78-4ec9-b560-81c61b04d654',
        name_en: 'Сок',
        name_kg: 'Сок',
        name_ru: 'Сок',
        description_en: '',
        description_kg: '',
        description_ru: '',
        price: 150,
        gram: '1000',
        category_name: 'Холдные',
        image: 'http://192.168.0.160:8000/media/dishes/0eac80f2b3_500.jpg',
        available_additives: []
    },
    {
        id: '9addf3e3-64f0-488b-9dc5-0b0ec64787a5',
        name_en: 'Куринный сет',
        name_kg: 'Куринный сет',
        name_ru: 'Куринный сет',
        description_en: '(Наггетсы, кур, голень, кур. крыл., кур. рулет., соус барбекю)',
        description_kg: '(Наггетсы, кур, голень, кур. крыл., кур. рулет., соус барбекю)',
        description_ru: '(Наггетсы, кур, голень, кур. крыл., кур. рулет., соус барбекю)',
        price: 1000,
        gram: '',
        category_name: 'Холодные закуски',
        image: 'http://192.168.0.160:8000/media/dishes/izobrazhenie_viber_2020-11-27_14-31-42_WfdKxPk.jpg',
        available_additives: []
    },
    {
        id: '729e8582-d13c-4642-b6c2-7468c5a1cba1',
        name_en: 'Ризотто',
        name_kg: 'Ризотто',
        name_ru: 'Ризотто',
        description_en: '',
        description_kg: '',
        description_ru: '',
        price: 70,
        gram: '',
        category_name: 'Гарниры',
        image: 'http://192.168.0.160:8000/media/dishes/rizotto-s-kuricey4.jpg',
        available_additives: []
    },
    {
        id: '946869fe-030b-4040-9c9f-a8f055847b8b',
        name_en: 'Рис',
        name_kg: 'Рис',
        name_ru: 'Рис',
        description_en: '',
        description_kg: '',
        description_ru: '',
        price: 60,
        gram: '',
        category_name: 'Гарниры',
        image: 'http://192.168.0.160:8000/media/dishes/1_V9uwzoZ.jpg',
        available_additives: []
    },
    {
        id: 'd0520fee-3bad-4215-8bd5-5c8cb0069cf2',
        name_en: 'Фри',
        name_kg: 'Фри',
        name_ru: 'Фри',
        description_en: '',
        description_kg: '',
        description_ru: '',
        price: 80,
        gram: '',
        category_name: 'Гарниры',
        image: 'http://192.168.0.160:8000/media/dishes/149279-ed4_wide.jpg',
        available_additives: []
    },
    {
        id: '55b2df60-20f4-408a-ab74-540bc84d91ba',
        name_en: 'Овощи гриль',
        name_kg: 'Овощи гриль',
        name_ru: 'Овощи гриль',
        description_en: '',
        description_kg: '',
        description_ru: '',
        price: 100,
        gram: '',
        category_name: 'Гарниры',
        image: 'http://192.168.0.160:8000/media/dishes/b7d6c53f.jpg',
        available_additives: []
    },
    {
        id: 'bf88aaa3-20eb-4258-b07b-fa9affdbf7c5',
        name_en: 'Крокеты',
        name_kg: 'Крокеты',
        name_ru: 'Крокеты',
        description_en: '',
        description_kg: '',
        description_ru: '',
        price: 100,
        gram: '',
        category_name: 'Гарниры',
        image: 'http://192.168.0.160:8000/media/dishes/big_273602.jpg',
        available_additives: []
    }
]