
export const data = [
    {
        "id": "b7339409-7796-4ca8-9824-d4038d1f1c6f",
        "name_en": "Tea",
        "name_kg": "Чай",
        "name_ru": "Чай",
        "description_en": "Tea is an aromatic beverage prepared by pouring hot or boiling water over cured or fresh leaves of Camellia sinensis, an evergreen shrub native to East Asia which probably originated in the borderlands of southwestern China and northern Myanmar. Tea is also rarely made from the leaves of Camellia taliensis. After plain water, tea is the most widely consumed drink in the world. There are many different types of tea; some have a cooling, slightly bitter, and astringent flavour, while others have vastly different profiles that include sweet, nutty, floral, or grassy notes. Tea has a stimulating effect in humans primarily due to its caffeine content.",
        "description_kg": "Чай өсүмдүгүнүн жалбырагы менен сабагынан алынуучу (солутуп, тоголоктоп, ферменттеп, кургатуу аркылуу) продукт. Өнөр жайда турдүү Чайлар чыгарылат. Алар мамили же чачылма Чай (Чай жалбырагы тоголоктолуп жасалат), кара жана көк Чай, ошондой эле такта Чай, кирпич Чай Даярдоо технологиясына карата көк Чай, сары Чай, кызыл Чайга бөлүнөт. Чайда кофеин, танин, теобромин, эфир майы, Р, С, Bj, В2 витаминдери болот.",
        "description_ru": "Чай — напиток, получаемый варкой, завариванием и/или настаиванием листа чайного куста, который предварительно подготавливается специальным образом. В названиях таких напитков к слову «чай», как правило, добавляется пояснение, характеризующее используемое сырьё («травяной чай», «ягодный чай», «фруктовый чай» и так далее). Чаепитие как традиция появилось в Китае.",
        "price": 20.0,
        "gram": 200,
        "category": "fcd8d1c2-797e-4b22-a875-85987bda7e93",
        "image": "https://aitenir.pythonanywhere.com/media/different-types-of-tea-FT-BLOG0621-7c7fd231e66d4fea8ca9a47cad52ba79_4nWux1s.jpg"
    },
    {
        "id": "cd9f04d0-c4ac-451d-84e3-bc7f97a99ec9",
        "name_en": "Sandwich",
        "name_kg": "Сэндвич",
        "name_ru": "Сэндвич",
        "description_en": "A sandwich is a food typically consisting of vegetables, sliced cheese or meat, placed on or between slices of bread, or more generally any dish wherein bread serves as a container or wrapper for another food type. The sandwich began as a portable, convenient finger food in the Western world, though over time it has become prevalent worldwide.",
        "description_kg": "Сэндвич - эки кесим нан жана алардын ортосуна бир аз толтурулган сэндвичтин бир түрү. Бир кесим нандан жасалган бутерброд англисче ачык бутерброд деп аталат.",
        "description_ru": "Сэндвич — вид бутерброда, состоящего из двух кусочков хлеба и какой-либо начинки между ними. Бутерброд из одного кусочка хлеба в английском языке называется открытым сэндвичем.",
        "price": 80.0,
        "gram": 200,
        "category": "b06e5329-2fe7-4a57-a0d7-cf1b3005d740",
        "image": "https://aitenir.pythonanywhere.com/media/food1.png"
    },
    {
        "id": "88a2cf03-edf9-45b9-98a2-ccc151c53d04",
        "name_en": "Beshbarmak",
        "name_kg": "Бешбармак",
        "name_ru": "Бешбармак",
        "description_en": "Kyrgyz's favorite dish made of finely chopped meat. Cooked meat is cut into pieces, noodles cooked in meat broth or dough cut into four squares[1] and fat (chopped onion, pepper, fat soup) are mixed to make beshbarmak.",
        "description_kg": "Майда тууралган эттен жасалган кыргыздын эң сый тамагы. Бышкан эт тууралып, эттин сорпосуна бышырылган кесме же төрт чарчы кесилген камыр[1] жана майлуу чык (тууралган пияз, калемпир, майлуу шорпо) аралаштырылып бешбармак жасалат.",
        "description_ru": "Любимое блюдо кыргызов из мелко нарезанного мяса. Вареное мясо режут на куски, сваренную на мясном бульоне лапшу или разрезанное на четыре квадрата тесто[1] и сало (нарезанный лук, перец, жирный суп) смешивают для приготовления бешбармака.",
        "price": 350.0,
        "gram": 450,
        "category": "b733d72f-3026-4c05-9d3b-ba72a1269258",
        "image": "https://aitenir.pythonanywhere.com/media/27_yokybN8.jpg"
    },
    {
        "id": "b36c074b-4884-4716-9ef3-881c306ea11e",
        "name_en": "Syrniki",
        "name_kg": "Сырники",
        "name_ru": "Сы́рники",
        "description_en": "Syrniki, curd cheese - a dish of Moldavian cuisine in the form of fried cakes made from cottage cheese and flour.",
        "description_kg": "Сырники, быштак - молдаван ашканасынын быштак жана ундан куурулган торт түрүндөгү тамагы.",
        "description_ru": "Сы́рники, творожники — блюдо и молдавской кухонь в виде обжаренных лепёшек из творога и муки.",
        "price": 150.0,
        "gram": 120,
        "category": "b06e5329-2fe7-4a57-a0d7-cf1b3005d740",
        "image": "https://aitenir.pythonanywhere.com/media/%D1%81%D1%8B%D1%80%D0%BD%D0%B8%D0%BA%D0%B8_3sKdp3y.jfif"
    },
    {
        "id": "c91f5cb9-55ae-49f8-a9cb-6974fd06bf72",
        "name_en": "pancakes",
        "name_kg": "куймак",
        "name_ru": "блины",
        "description_en": "Pancakes are round, fried, thin, rich cakes made from batter.",
        "description_kg": "Куймак — камырдан жасалган тегерек, куурулган, жука, бай торттор.",
        "description_ru": "Блины представляют собой круглые жаренные тонкие сдобные лепешки, приготовленные из жидкого теста.",
        "price": 160.0,
        "gram": 140,
        "category": "b06e5329-2fe7-4a57-a0d7-cf1b3005d740",
        "image": "https://aitenir.pythonanywhere.com/media/%D0%BA%D1%83%D0%B9%D0%BC%D0%B0.jfif"
    },
    {
        "id": "729f4e14-05df-469e-8009-ff1213f38c8d",
        "name_en": "Granola",
        "name_kg": "Гранола",
        "name_ru": "Гранола",
        "description_en": "Granola - containing rolled oatmeal, nuts and honey, which are baked to a crispy state.",
        "description_kg": "Гранола - кытырак абалга чейин бышырылган прокат сулу, жаңгактар ​​жана бал камтыган.",
        "description_ru": "Гранола —  содержащее плющеную овсяную крупу, орехи и мёд,  которые  запечены до хрустящего состояния.",
        "price": 150.0,
        "gram": 200,
        "category": "b06e5329-2fe7-4a57-a0d7-cf1b3005d740",
        "image": "https://aitenir.pythonanywhere.com/media/%D0%93%D1%80%D0%B0%D0%BD%D0%BE%D0%BB%D0%B0.jfif"
    },
    {
        "id": "d5d7a53a-b3b2-4d69-8a9d-4eb0ac703259",
        "name_en": "Olivier",
        "name_kg": "Оливье",
        "name_ru": "Оливье",
        "description_en": "Olivier is a snack salad of Russian cuisine made of boiled carrots, pickled cucumbers, eggs with meat or boiled sausage in mayonnaise dressing.",
        "description_kg": "Оливье - кайнатылган тамыр жашылчаларынан, туздалган бадыраңдан, эт менен жумурткадан же майонезге бышырылган колбасадан жасалган орус ашканасынын табити салат.",
        "description_ru": "Оливье — закусочный салат русской кухни из отварных корнеплодов, солёных огурцов, яиц с мясом или варёной колбасой в майонезной заправке.",
        "price": 350.0,
        "gram": 300,
        "category": "bfdd05bb-6744-42e7-b884-8271769e773c",
        "image": "https://aitenir.pythonanywhere.com/media/%D0%BE%D0%BB%D0%B8%D0%B2%D1%8C%D0%B5.jfif"
    },
    {
        "id": "c1274118-a0b2-4d83-b11c-b7ecdb8c2424",
        "name_en": "Caesar",
        "name_kg": "Цезарь",
        "name_ru": "Цезарь",
        "description_en": "Green salad,Tomatoes,Chicken fillet,White bread,Sauce \"Caesar\",Butter,Garlic,parmesan cheese,PARMESAN CHEESE",
        "description_kg": "Жашыл салат,помидортоок филеси,Ак нан,Соус \"Цезарь\",май,Сарымсак,пармезан сыр,ПАРМАЗАН СЫРЫ",
        "description_ru": "Зеленый салат,Помидоры,Куриное филе,Белый хлеб,Соус «Цезарь»,Сливочное масло,Чеснок,Сырпармезан,СЫР ПАРМЕЗАН",
        "price": 250.0,
        "gram": 200,
        "category": "bfdd05bb-6744-42e7-b884-8271769e773c",
        "image": "https://aitenir.pythonanywhere.com/media/%D1%86%D0%B5%D0%B7%D0%B0%D1%80%D1%8C.jpg"
    },
    {
        "id": "0603c284-747d-4964-bf92-8de1b09c9b35",
        "name_en": "Dollar",
        "name_kg": "Доллар",
        "name_ru": "Доллар",
        "description_en": "cucumbers, Beef, Onions,red sweet pepper,Garlic,ground red pepper,Sugar,ground coriander,Salt,\r\nVegetable oil",
        "description_kg": "бадыраң, уй эти, пияз, кызыл таттуу калемпир, сарымсак, майдаланган кызыл калемпир, шекер, майдаланган кориандр, туз,\r\nӨсүмдүк майы",
        "description_ru": "огурцы, Говядина, Лук репчатый, перец сладкий красный, чеснок, перец красный молотый, сахар, кориандр молотый, соль,\r\nРастительное масло",
        "price": 300.0,
        "gram": 210,
        "category": "bfdd05bb-6744-42e7-b884-8271769e773c",
        "image": "https://aitenir.pythonanywhere.com/media/%D0%B4%D0%BE%D0%BB%D0%BB%D0%B0%D1%80.jfif"
    },
    {
        "id": "09fac64e-f584-4132-bd6d-edbc87b33944",
        "name_en": "Peporoni",
        "name_kg": "Пепорони",
        "name_ru": "Пепорони",
        "description_en": "Yeast, flour, vegetable oil, salt, sugar, tomato paste, sausage, mozzarella cheese",
        "description_kg": "Ачыткы, ун, өсүмдүк майы, туз, кант, томат пастасы, колбаса, моцарелла сыры",
        "description_ru": "Дрожжи,Мука,Масло растительное,Соль,Сахар,Томатная паста,Колбаса,Сыр моцарелла",
        "price": 500.0,
        "gram": 450,
        "category": "5e61b742-d303-4daa-bddf-3fae745f0959",
        "image": "https://aitenir.pythonanywhere.com/media/%D0%BF%D0%B5%D0%BF.jfif"
    },
    {
        "id": "5f20e049-10bf-4908-82f0-b3b355ec518b",
        "name_en": "Italy",
        "name_kg": "Италия",
        "name_ru": "Италия",
        "description_en": "Pizza dough,Tomato sauce,Mozzarella cheese for pizza,Parma ham,Mascarpone cheese,Parmesan cheese,Arugula,Truffle oil,Spices",
        "description_kg": "Пиццанын камыры, Помидор соусу, Пицца үчүн Моцарелла сыры, Парма ветчина, Маскарпоне сыры, Пармезан сыры, рукола, Трюфель майы, Татымалдар",
        "description_ru": "Тесто для пиццы,Томатный соус,Сыр моцарелла для пиццы,Пармская ветчина,Сыр маскарпоне,Сыр пармезан,Рукола,Трюфельное масло,Специи",
        "price": 550.0,
        "gram": 450,
        "category": "5e61b742-d303-4daa-bddf-3fae745f0959",
        "image": "https://aitenir.pythonanywhere.com/media/%D0%B8%D1%82%D0%B0%D0%BB%D0%B8%D1%8F.jfif"
    },
    {
        "id": "83c62e9a-1994-49b2-be14-51150e285ee0",
        "name_en": "Hawayana",
        "name_kg": "Хаваяна",
        "name_ru": "Хаваяна",
        "description_en": "flour, water, vegetable oil (preferably olive oil), sugar, salt, dry yeast (high-speed)",
        "description_kg": "ун, суу, өсүмдүк майы (жакшы зайтун майы), кант, туз, кургак ачыткы (жогорку ылдамдыкта)",
        "description_ru": "муки,воды, растительного масла (желательно оливкового),сахара, соли,сухих дрожжей (быстродействующих)",
        "price": 450.0,
        "gram": 450,
        "category": "5e61b742-d303-4daa-bddf-3fae745f0959",
        "image": "https://aitenir.pythonanywhere.com/media/%D1%85%D0%B0%D0%B2%D0%B0%D1%8F%D0%BD%D0%B2.jfif"
    },
    {
        "id": "e03114c8-1105-44da-a975-495811456cc1",
        "name_en": "Macarons",
        "name_kg": "Макаронсы",
        "name_ru": "Макаронсы",
        "description_en": "Almond flour, Powdered sugar, Egg white, Sugar, Water, Egg white, Food coloring, Raspberry, Dark chocolate, Cream",
        "description_kg": "Бадам уну, кант упасы, жумуртканын агы, кант, суу, жумуртканын агы, тамак-аш боёгу, малина, кара шоколад, крем",
        "description_ru": "Мука миндальная,Сахарная пудра ,Белок яичный,Сахар,Вода,Белок яичный,Краситель пищевой,Малина,Шоколад темный,Сливки",
        "price": 1400.0,
        "gram": 500,
        "category": "f38b8b75-991c-4ad2-9e19-13443e1c3708",
        "image": "https://aitenir.pythonanywhere.com/media/%D0%BC%D0%B0%D0%BA%D0%B0%D1%80%D0%BE%D0%BD%D1%81%D1%8B.jpg"
    },
    {
        "id": "f9bf3b75-cfaf-4a7b-b4d5-a7097e6516a5",
        "name_en": "San Sebastian",
        "name_kg": "Сан Себастьян",
        "name_ru": "Сан-Себастьян",
        "description_en": "Cream cheese, Cream, Sugar, Chicken eggs, Wheat flour, Vanilla sugar, Milk chocolate",
        "description_kg": "Крем сыр, каймак, кант, тоок жумурткасы, буудай уну, ваниль канты, сүт шоколады",
        "description_ru": "Сливочный сыр,Сливки,Сахар,Куриные яйца,Пшеничная мука,Ванильный сахар,Молочный шоколад",
        "price": 340.0,
        "gram": 90,
        "category": "f38b8b75-991c-4ad2-9e19-13443e1c3708",
        "image": "https://aitenir.pythonanywhere.com/media/cfy.jfif"
    },
    {
        "id": "5447eac8-610d-464b-b87c-af431fdeedcd",
        "name_en": "Chokolate biscuit",
        "name_kg": "шоколад печенье",
        "name_ru": "Шоколадный бисквит",
        "description_en": "Flour, Cocoa powder, Butter, Eggs, Yolks, Sugar, Salt, Vanilla sugar",
        "description_kg": "Ун, какао, сары май, жумуртка, сарысы, шекер, туз, ваниль",
        "description_ru": "Мука,Какао порошок,Масло сливочное,Яйца,Желтки,Сахар,Соль,Ванильный сахар",
        "price": 150.0,
        "gram": 70,
        "category": "f38b8b75-991c-4ad2-9e19-13443e1c3708",
        "image": "https://aitenir.pythonanywhere.com/media/choko.jfif"
    },
    {
        "id": "53d81ef8-2870-4353-b5d0-f375f2c01649",
        "name_en": "Manti",
        "name_kg": "Манты",
        "name_ru": "Манты",
        "description_en": "Flour, meat, onion,",
        "description_kg": "Ун, эт, пияз,",
        "description_ru": "Мук,мясо,лук,",
        "price": 150.0,
        "gram": 300,
        "category": "b733d72f-3026-4c05-9d3b-ba72a1269258",
        "image": "https://aitenir.pythonanywhere.com/media/%D0%BC%D0%B0%D0%BD%D1%82%D1%8B_FntdX9N.jfif"
    },
    {
        "id": "ffbdd1c0-544f-484d-95e4-d3ffdd684f53",
        "name_en": "Kuurdak",
        "name_kg": "Куурдак",
        "name_ru": "Куурдак",
        "description_en": "Potatoes, meat, onions, salt",
        "description_kg": "Картошка, эт, пияз, туз",
        "description_ru": "Картошка,мясо,лук,соль",
        "price": 350.0,
        "gram": 300,
        "category": "b733d72f-3026-4c05-9d3b-ba72a1269258",
        "image": "https://aitenir.pythonanywhere.com/media/%D0%BA%D1%83%D1%83%D1%80%D0%B4%D0%B0%D0%BA_dWID19S.jfif"
    },
    {
        "id": "bcb2c181-d390-4fba-8dc3-3f269f81ed5b",
        "name_en": "Celery juice",
        "name_kg": "Сельдерей ширеси",
        "name_ru": "сок из сельдерея",
        "description_en": "Banana, apple, celery and fresh herbs",
        "description_kg": "Банан, алма, сельдерей жана жаңы чөптөр",
        "description_ru": "Банана, яблока, сельдерея и свежей зелени",
        "price": 30.0,
        "gram": 100,
        "category": "1b7274d6-badd-41e4-8fca-d7db7d724f0b",
        "image": "https://aitenir.pythonanywhere.com/media/%D1%8F%D1%8F.jfif"
    },
    {
        "id": "a9388892-4df5-4ec0-bb93-3515a7096755",
        "name_en": "Orange juice",
        "name_kg": "Апельсин ширеси",
        "name_ru": "Сок апельсиновый",
        "description_en": "Orange,water",
        "description_kg": "Апельсин,суу",
        "description_ru": "Апельсин,Вода",
        "price": 40.0,
        "gram": 140,
        "category": "1b7274d6-badd-41e4-8fca-d7db7d724f0b",
        "image": "https://aitenir.pythonanywhere.com/media/%D1%8B%D1%89%D0%BB.jpg"
    },
    {
        "id": "7a3ae293-54e7-450a-8e9a-5f7214b78781",
        "name_en": "Apple juice",
        "name_kg": "Алма ширеси",
        "name_ru": "Яблочный сок",
        "description_en": "Аpples, water",
        "description_kg": "Алма, суу",
        "description_ru": "Яблока,вода",
        "price": 30.0,
        "gram": 140,
        "category": "1b7274d6-badd-41e4-8fca-d7db7d724f0b",
        "image": "https://aitenir.pythonanywhere.com/media/%D1%8F%D0%B1%D0%BB%D0%BE%D0%BA%D0%B0.jfif"
    },
    {
        "id": "3e7628f2-dd8d-4cf4-9d55-541aa882a9b2",
        "name_en": "Сoffee",
        "name_kg": "Кофе",
        "name_ru": "Кофе",
        "description_en": "Banana milk, espresso",
        "description_kg": "Банан сүтү, эспрессо",
        "description_ru": "Банановое молоко,эспрессо",
        "price": 20.0,
        "gram": 140,
        "category": "fcd8d1c2-797e-4b22-a875-85987bda7e93",
        "image": "https://aitenir.pythonanywhere.com/media/%D0%BA%D0%BE%D1%84%D0%B5.jfif"
    },
    {
        "id": "25713692-d241-42b8-a792-8defb8b01629",
        "name_en": "Cappuccino",
        "name_kg": "Каппучино",
        "name_ru": "Капучино",
        "description_en": "Coffee, milk, sugar",
        "description_kg": "Кофе, сүт, кант",
        "description_ru": "Кофе,молоко,сахар",
        "price": 100.0,
        "gram": 140,
        "category": "fcd8d1c2-797e-4b22-a875-85987bda7e93",
        "image": "https://aitenir.pythonanywhere.com/media/%D0%BA%D0%B0%D0%BF%D0%BF%D1%83%D1%87%D0%B8%D0%BD%D0%BE.jfif"
    },
    {
        "id": "cde3f324-3c68-455b-ba08-817bd5169aaf",
        "name_en": "Cappuccino",
        "name_kg": "Каппучино",
        "name_ru": "Капучино",
        "description_en": "Coffee, milk, sugar",
        "description_kg": "Кофе, сүт, кант",
        "description_ru": "Кофе,молоко,сахар",
        "price": 100.0,
        "gram": 140,
        "category": "c53cb4dc-fd24-461f-99c1-2ad2e932e237",
        "image": "https://aitenir.pythonanywhere.com/media/%D0%BA%D0%B0%D0%BF%D0%BF%D1%83%D1%87%D0%B8%D0%BD%D0%BE_QbyYD66.jfif"
    }
]