import uniqid from "uniqid"
export const data = [
   [
    {
    id: uniqid(),
    title: "Pancake",
    title_ru: "Панкейк",
    title_kg: "Панкейк",
    desc: "Flour, milk, banana, powdered sugar, currant",
    desc_ru: "Мука, молоко, банан, сахарная пудра,смородина",
    desc_kg: "Ун, сүт, банан, кант упасы, карагат",
    quantity: 0,
    price: 150,
    image: "https://static.1000.menu/res/640/img/content-v2/18/ae/13309/pankeiki-na-moloke_1614588045_9_max.jpg",
    mass: 240,
    top: true,
  },
    {
       id: uniqid(),
       title: "Pancake",
       title_ru: "Панкейк",
       title_kg: "Панкейк",
       desc: "Flour, milk, banana, powdered sugar, currant",
       desc_ru: "Мука, молоко, банан, сахарная пудра,смородина",
       desc_kg: "Ун, сүт, банан, кант упасы, карагат",
       quantity: 0,
       price: 150,
       image: "https://static.1000.menu/res/640/img/content-v2/18/ae/13309/pankeiki-na-moloke_1614588045_9_max.jpg",
       mass: 240,
       top: true,
     },
     {
       id: uniqid(),
       title: "Pancake",
       title_ru: "Панкейк",
       title_kg: "Панкейк",
       desc: "Flour, milk, banana, powdered sugar, currant",
       desc_ru: "Мука, молоко, банан, сахарная пудра,смородина",
       desc_kg: "Ун, сүт, банан, кант упасы, карагат",
       quantity: 0,
       price: 150,
       image: "https://static.1000.menu/res/640/img/content-v2/18/ae/13309/pankeiki-na-moloke_1614588045_9_max.jpg",
       mass: 240,
       top: true,
     },
     {
       id: uniqid(),
       title: "Pancake",
       title_ru: "Панкейк",
       title_kg: "Панкейк",
       desc: "Flour, milk, banana, powdered sugar, currant",
       desc_ru: "Мука, молоко, банан, сахарная пудра,смородина",
       desc_kg: "Ун, сүт, банан, кант упасы, карагат",
       quantity: 0,
       price: 150,
       image: "https://static.1000.menu/res/640/img/content-v2/18/ae/13309/pankeiki-na-moloke_1614588045_9_max.jpg",
       mass: 240,
       top: true,
     },
     {
       id: uniqid(),
       title: "Pancake",
       title_ru: "Панкейк",
       title_kg: "Панкейк",
       desc: "Flour, milk, banana, powdered sugar, currant",
       desc_ru: "Мука, молоко, банан, сахарная пудра,смородина",
       desc_kg: "Ун, сүт, банан, кант упасы, карагат",
       quantity: 0,
       price: 150,
       image: "https://static.1000.menu/res/640/img/content-v2/18/ae/13309/pankeiki-na-moloke_1614588045_9_max.jpg",
       mass: 240,
       top: true,
     },
     {
       id: uniqid(),
       title: "Pancake",
       title_ru: "Панкейк",
       title_kg: "Панкейк",
       desc: "Flour, milk, banana, powdered sugar, currant",
       desc_ru: "Мука, молоко, банан, сахарная пудра,смородина",
       desc_kg: "Ун, сүт, банан, кант упасы, карагат",
       quantity: 0,
       price: 150,
       image: "https://static.1000.menu/res/640/img/content-v2/18/ae/13309/pankeiki-na-moloke_1614588045_9_max.jpg",
       mass: 240,
       top: true,
     },
], [
  {
    id: uniqid(),
    title: "Pancake",
    title_ru: "Панкейк",
    title_kg: "Панкейк",
    desc: "Soft, sweet, delicious American pancakes, also known as pancakes, go great with honey. Pancakes will appeal to both adults and children. Pancakes with milk will be an excellent breakfast.",
    desc_ru: "Мягкие, сладкие, вкусные американские блинчики, которые еще называют панкейки (pancakes), отлично сочетаются с медом. Панкейки понравятся и взрослым, и детям. Блинчики на молоке станут отличным завтраком.",
    desc_kg: "Жумшак, таттуу, даамдуу америкалык куймактар, ошондой эле куймак деп аталат, бал менен сонун кетет. Блин чоңдорго да, балдарга да жагат. Сүт менен куймак сонун эртең мененки тамак болот.",
    ingredients: "Flour, milk, banana, powdered sugar, currant",
    ingredients_ru: "Мука, молоко, банан, сахарная пудра,смородина",
    ingredients_kg: "Ун, сүт, банан, кант упасы, карагат",
    quantity: 0,
    price: 150,
    image: "dfghj",
    mass: 240,
    top: true,
  },
  {
    id: uniqid(),
    title: "Lazy Tongues Lettuce",
    title_ru: "Ленивые язычки салат",
    title_kg: "Панкейк",
    desc: "Soft, sweet, delicious American pancakes, also known as pancakes, go great with honey. Pancakes will appeal to both adults and children. Pancakes with milk will be an excellent breakfast.",
    desc_ru: "Мягкие, сладкие, вкусные американские блинчики, которые еще называют панкейки (pancakes), отлично сочетаются с медом. Панкейки понравятся и взрослым, и детям. Блинчики на молоке станут отличным завтраком.",
    desc_kg: "Жумшак, таттуу, даамдуу америкалык куймактар, ошондой эле куймак деп аталат, бал менен сонун кетет. Блин чоңдорго да, балдарга да жагат. Сүт менен куймак сонун эртең мененки тамак болот.",
    ingredients: "Flour, milk, banana, powdered sugar, currant",
    ingredients_ru: "Мука, молоко, банан, сахарная пудра,смородина",
    ingredients_kg: "Ун, сүт, банан, кант упасы, карагат",
    quantity: 0,
    price: 150,
    image: "https://static.1000.menu/res/640/img/content-v2/18/ae/13309/pankeiki-na-moloke_1614588045_9_max.jpg",
    mass: 240,
    top: true,
  },
], [
    {
      id: uniqid(),
      title: "Pancake",
      title_ru: "Панкейк",
      title_kg: "Панкейк",
      desc: "Soft, sweet, delicious American pancakes, also known as pancakes, go great with honey. Pancakes will appeal to both adults and children. Pancakes with milk will be an excellent breakfast.",
      desc_ru: "Мягкие, сладкие, вкусные американские блинчики, которые еще называют панкейки (pancakes), отлично сочетаются с медом. Панкейки понравятся и взрослым, и детям. Блинчики на молоке станут отличным завтраком.",
      desc_kg: "Жумшак, таттуу, даамдуу америкалык куймактар, ошондой эле куймак деп аталат, бал менен сонун кетет. Блин чоңдорго да, балдарга да жагат. Сүт менен куймак сонун эртең мененки тамак болот.",
      ingredients: "Flour, milk, banana, powdered sugar, currant",
      ingredients_ru: "Мука, молоко, банан, сахарная пудра,смородина",
      ingredients_kg: "Ун, сүт, банан, кант упасы, карагат",
      quantity: 0,
      price: 150,
      image: "https://static.1000.menu/res/640/img/content-v2/18/ae/13309/pankeiki-na-moloke_1614588045_9_max.jpg",
      mass: 240,
      top: true,
    },
    {
      id: uniqid(),
      title: "Lazy Tongues Lettuce",
      title_ru: "Ленивые язычки салат",
      title_kg: "Панкейк",
      desc: "Soft, sweet, delicious American pancakes, also known as pancakes, go great with honey. Pancakes will appeal to both adults and children. Pancakes with milk will be an excellent breakfast.",
      desc_ru: "Мягкие, сладкие, вкусные американские блинчики, которые еще называют панкейки (pancakes), отлично сочетаются с медом. Панкейки понравятся и взрослым, и детям. Блинчики на молоке станут отличным завтраком.",
      desc_kg: "Жумшак, таттуу, даамдуу америкалык куймактар, ошондой эле куймак деп аталат, бал менен сонун кетет. Блин чоңдорго да, балдарга да жагат. Сүт менен куймак сонун эртең мененки тамак болот.",
      ingredients: "Flour, milk, banana, powdered sugar, currant",
      ingredients_ru: "Мука, молоко, банан, сахарная пудра,смородина",
      ingredients_kg: "Ун, сүт, банан, кант упасы, карагат",
      quantity: 0,
      price: 150,
      image: "https://static.1000.menu/res/640/img/content-v2/18/ae/13309/pankeiki-na-moloke_1614588045_9_max.jpg",
      mass: 240,
      top: true,
    },
  ],
]



