export const GET_BASKET = "GET_BASKET"
export const PLUS = "GET_BASKET"
export const MINUS = "GET_BASKET"
export const DELETE = "GET_BASKET"
export const MODAL = "MODAL"
export const SEARCH = "SEARCH"