export const GET_BASKET = "GET_BASKET"
export const EMPTY_BASKET = "EMPTY_BASKET"
export const GET_FOODS = "GET_FOODS"
export const GET_CHECK = "GET_CHECK"
export const TOKEN_ID = "TOKEN_ID"
export const ADD = "ADD"
export const MODAL_TO_BASKET = "MODAL_TO_BASKET"
export const MODAL_TO_PRICE = "MODAL_TO_PRICE"
export const GET_DETAIL = "GET_DETAIL"
export const GET_PARAMS = "GET_PARAMS"
export const PLUS = "PLUS"
export const MINUS = "MINUS"
export const DELETE = "DELETE"
export const MODAL = "MODAL"
export const MODAL_PLUS = "MODAL_PLUS"
export const MODAL_MINUS = "MODAL_MINUS"
export const SEARCH = "SEARCH"
export const HERE = "HERE"
export const WITH = "WITH"
export const CASH = "CASH"
export const TERMINAL = "TERMINAL"

export const BURGER_MENU = "BURGER_MENU"

